function loadOptionsWhenExist(gui)
% Syntax:
%
% loadOptionsWhenExist(gui)
%
% Description:
%
% Part of DAG. When the save name is found in the graphs property of the
% objects parent we ask the user if it will rename, overwrite or
% exit without saving the loaded graph.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen

    % Create the window
    currentMonitor    = nb_getCurrentMonitor();
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    f = figure('Visible',     'off',...
               'units',       'characters',...
               'position',    [50 40 100 20],...
               'name',        [gui.parent.guiName ': Import Option'],...
               'NumberTitle', 'off',...
               'MenuBar',     'None',...
               'Toolbar',     'None',...
               'dockControls','off',...
               'resize',      'off',...
               'windowStyle', 'modal',...
               'Color',       defaultBackground);           
    nb_moveFigureToMonitor(f,currentMonitor,'center');                   

    % Print question message
    message = ['The graph package ''' gui.name ''' already exist, what do you want to do?'];
    uicontrol('parent',             f,...
              'units',              'normalized',...
              'position',           [0.04 0.25 0.96 0.4],...
              'Style',              'text',...
              'HorizontalAlignment','left',...
              'String',             message); 

    % Push buttons to give an answer
    %--------------------------------------------------------------
    bHeight = 0.1;
    bWidth  = 0.15;
    space   = 0.1;
    start   = (1 - bWidth*3 - space*2)/2;
    ySpace  = 0.1;

    uicontrol(f,...
                     'units',       'normalized',...
                     'position',    [start,ySpace,bWidth,bHeight],...
                     'callback',    @gui.exit,...
                     'String',      'Cancel',...
                     'Style',       'pushbutton');

    uicontrol(f,...
                     'units',       'normalized',...
                     'position',    [start + bWidth + space,ySpace,bWidth,bHeight],...
                     'callback',    @gui.overwrite,...
                     'String',      'Overwrite',...
                     'Style',       'pushbutton');
                 
    uicontrol(f,...
                     'units',       'normalized',...
                     'position',    [start + bWidth*2 + space*2,ySpace,bWidth,bHeight],...
                     'callback',    @gui.rename,...
                     'String',      'Rename',...
                     'Style',       'pushbutton');             

    % Make the GUI visible.
    %--------------------------------------------------------------
    set(f,'Visible','on'); 

end
