function selectVariablesPanel(gui)
% Syntax:
%
% selectVariablesPanel(gui)
%
% Description:
%
% Part of DAG. Creates a panel for selecting fan variables.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen

    plotterT = gui.plotter;

    % Create panel
    %--------------------------------------------------------------
    mm = uipanel('parent',              gui.figureHandle,...
                  'title',               '',...
                  'visible',             'on',...
                  'borderType',          'none',... 
                  'units',               'normalized',...
                  'position',            [0, 0, 1, 1]); 
    gui.panelHandle1 = mm;
    
    % Locations  
    %--------------------------------------------------------------
    ySpace       = 0.04;
    startList    = 0.14;
    vListHeight  = 1 - startList - ySpace*2;
    extra        = 0.01;
    startListX1  = 0.04;
    listWidth    = 0.4;
    startListX2  = 1 - startListX1 - listWidth;
    space        = startListX2 - startListX1 - listWidth;
    buttonSize   = 0.06;

    % Plotted variable list
    %--------------------------------------------------------------
    uicontrol(...
                   'units',       'normalized',...
                   'position',    [startListX1, startList + extra + vListHeight, listWidth, 0.04],...
                   'parent',      mm,...
                   'style',       'text',...
                   'string',      'Variables'); 

    varList = uicontrol('units',       'normalized',...
                     'position',    [startListX1, startList, listWidth, vListHeight],...
                     'parent',      mm,...
                     'background',  [1 1 1],...
                     'style',       'listbox',...
                     'string',      plotterT.DB.variables,...
                     'max',         size(plotterT.DB.variables,2)); 

    % Fan variables list 
    %--------------------------------------------------------------
    uicontrol(...
                   'units',       'normalized',...
                   'position',    [startListX2, startList + vListHeight + extra, listWidth, 0.04],...
                   'parent',      mm,...
                   'style',       'text',...
                   'string',      'Fan variables'); 
               
    fanVars = plotterT.fanVariables;           

    selList = uicontrol(...
                     'units',       'normalized',...
                     'position',    [startListX2, startList, listWidth, vListHeight],...
                     'parent',      mm,...
                     'background',  [1 1 1],...
                     'style',       'listbox',...
                     'string',      fanVars);
    gui.handle1 = selList;             

    % Create add variable to selected button 
    posB1 = [startListX1 + listWidth + space/2 - buttonSize/2, startList + vListHeight/2 + vListHeight/10 - buttonSize/2, buttonSize, buttonSize];
    uicontrol(...
                   'units',       'normalized',...
                   'position',    posB1,...
                   'parent',      mm,...
                   'style',       'pushbutton',...
                   'string',      '>',...
                   'callback',    {@select,varList,selList}); 

    %  Create remove variable to selected button
    posB2 = [startListX1 + listWidth + space/2 - buttonSize/2, startList + vListHeight/2 - vListHeight/10 - buttonSize/2, buttonSize, buttonSize];
    uicontrol(...
                   'units',       'normalized',...
                   'position',    posB2,...
                   'parent',      mm,...
                   'style',       'pushbutton',...
                   'string',      '<',...
                   'callback',    {@deSelect,selList}); 
                 
    % Next button      
    %-------------------------------------------------------------- 
    buttonHeight = 0.05;
    buttonWidth  = 0.2;
    buttonXLoc   = 0.75 - buttonWidth/2;
    buttonYLoc   = startList/2 - buttonHeight/2;
    
    uicontrol(...
              'units',              'normalized',...
              'position',           [buttonXLoc, buttonYLoc, buttonWidth, buttonHeight],...
              'parent',             mm,...
              'style',              'pushbutton',...
              'Interruptible',      'off',...
              'horizontalAlignment','left',...
              'string',             'Next',...
              'callback',           @gui.setFanVariables); 
    
end

%==================================================================
% SUB
%==================================================================

function select(hObject,event,varList,selList)
        
    % Get selected variables
    indexT  = get(varList,'value');
    stringT = get(varList,'string');
    vars    = stringT(indexT);

    % Ensure no overlapping variables
    oldVars = get(selList,'string');
    if ~isempty(oldVars) 
        indexT   = ismember(vars,oldVars);
        newVars  = vars(~indexT);
        vars     = [newVars; oldVars];
    end

    % Update the list of the removed variables
    set(selList,'string',sort(vars),'value',1,'max',length(vars));

end

function deSelect(hObject,event,selList)

    % Get selected variables
    indexT     = get(selList,'value');
    stringT    = get(selList,'string');
    varsToDel  = stringT(indexT);

    % Find out which to keep
    indexT     = ismember(stringT,varsToDel);
    varsToKeep = stringT(~indexT);

    % Update the list of the selected variables
    if isempty(varsToKeep)
        set(selList,'string',varsToKeep);%,'value',[],'max',[]);
    else
        set(selList,'string',varsToKeep,'value',1,'max',length(varsToKeep));
    end

end
