function makeGUI(gui)
% Syntax:
%
% makeGUI(gui)
%
% Description:
%
% Part of DAG.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    currentMonitor    = nb_getCurrentMonitor();
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    f = figure('visible',        'off',...
               'units',          'characters',...
               'position',       [65   15  70   30],...
               'Color',          defaultBackground,...
               'name',           gui.name,...
               'numberTitle',    'off',...
               'menuBar',        'None',...
               'toolBar',        'None',...
               'windowStyle',    'modal',...
               'resize',         'off');
    gui.figureHandle = f; 
    nb_moveFigureToMonitor(f,currentMonitor,'center');
    
    % Panel with graph selection list
    xSpace     = 0.04;
    ySpace     = 0.04;   
    startY     = 0.32;
    listWidth  = 0.92;
    heightY    = 1 - startY - ySpace;
    uip = uipanel('parent',              f,...
                  'title',               'Select',...
                  'units',               'normalized',...
                  'position',            [xSpace, startY, listWidth, heightY]);
    
    % List the cellstr to select from
    gui.listbox = uicontrol(...
                     'units',       'normalized',...
                     'position',    [0.04, 0.02, 0.92, 0.96],...
                     'parent',      uip,...
                     'background',  [1 1 1],...
                     'style',       'listbox',...
                     'string',      gui.cstr,...
                     'max',         length(gui.cstr));
                                              
    % Create the finished button
    bWidth  = 0.2;
    bHeight = 0.05;
    bX      = 0.5 - bWidth/2;
    bY      = (startY - bHeight)/2; 
    uicontrol('units',          'normalized',...
              'position',       [bX, bY, bWidth, bHeight],...
              'parent',         f,...
              'style',          'pushbutton',...
              'Interruptible',  'off',...
              'string',         'Finish',...
              'callback',       @gui.finishCallback);      
    
    
    % Make it visible
    set(f,'visible','on')

end
