function tablePanel(gui)
% Syntax:
%
% tablePanel(gui)
%
% Description:
%
% Part of DAG.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    % Get graph object 
    plotterT = gui.plotter;

    % Create panel
    %--------------------------------------------------------------
    uip = uipanel('parent',              gui.figureHandle,...
                  'title',               '',...
                  'visible',             'on',...
                  'borderType',          'none',... 
                  'units',               'normalized',...
                  'position',            [0.22, 0.02, 1 - 0.24, 0.96]); 
    gui.panelHandle1 = uip;
    
    startPopX = 0.3;
    widthPop  = 0.35;
    heightPop = 0.055;
    startTX   = 0.04;
    widthT    = widthPop - startTX*2;
    heightT   = 0.053;
    kk        = 9;
    spaceYPop = (1 - heightPop*kk)/(kk +1);
    extra     = -(heightPop - heightT)*5;
    
    % Position
    %--------------------------------------------------------------
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Position');

    pos      = plotterT.position;
    space    = 0.02;
    widthPos = widthPop/4 - space*3/4;
    
    uicontrol(...
              'units',              'normalized',...
              'position',           [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPos, heightPop],...
              'parent',             uip,...
              'background',         [1 1 1],...
              'style',              'edit',...
              'Interruptible',      'off',...
              'horizontalAlignment','right',...
              'string',             num2str(pos(1)),...
              'callback',           {@gui.setPosition,1}); 
    
    uicontrol(...
              'units',              'normalized',...
              'position',           [startPopX + widthPos + space, heightPop*(kk-1) + spaceYPop*kk, widthPos, heightPop],...
              'parent',             uip,...
              'background',         [1 1 1],...
              'style',              'edit',...
              'Interruptible',      'off',...
              'horizontalAlignment','right',...
              'string',             num2str(pos(2)),...
              'callback',           {@gui.setPosition,2}); 
          
    uicontrol(...
              'units',              'normalized',...
              'position',           [startPopX + widthPos*2 + space*2, heightPop*(kk-1) + spaceYPop*kk, widthPos, heightPop],...
              'parent',             uip,...
              'background',         [1 1 1],...
              'style',              'edit',...
              'Interruptible',      'off',...
              'horizontalAlignment','right',...
              'string',             num2str(pos(3)),...
              'callback',           {@gui.setPosition,3}); 
          
    uicontrol(...
              'units',              'normalized',...
              'position',           [startPopX + widthPos*3 + space*3, heightPop*(kk-1) + spaceYPop*kk, widthPos, heightPop],...
              'parent',             uip,...
              'background',         [1 1 1],...
              'style',              'edit',...
              'Interruptible',      'off',...
              'horizontalAlignment','right',...
              'string',             num2str(pos(4)),...
              'callback',           {@gui.setPosition,4});    
          
    % Mode
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Adjust mode');

    
    options   = {'Even','Neighbour'};
    [~,value] = nb_ismemberi(plotterT.table.mode,options);
    if isempty(value)
        value =1;
    end

    uicontrol(...
              'units',          'normalized',...
              'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',         uip,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'Interruptible',  'off',...
              'string',         options,...
              'value',          value,....
              'callback',       {@gui.set,'mode'});
    
end
