function makeGUI(gui)
% Syntax:
%
% makeGUI(gui)
%
% Description:
%
% Part of DAG.
% 
% Written by Kenneth Sæterhagen Paulsen
    plotterT = gui.plotter;
    parent   = gui.plotter.parent;
    
% Copyright (c) 2021, Kenneth Sæterhagen Paulsen

    % Check if we are dealing with Dates vs Dates Plot
    include  = true;      
    callback = @gui.setPlotType;
    if isa(plotterT,'nb_graph_ts')      
          if ~isempty(plotterT.datesToPlot)
              include  = false;
              callback = @gui.setPlotTypeWhenDatesToPlot;
          end
    end
    
    if isa(plotterT,'nb_graph_ts') || isa(plotterT,'nb_graph_data') 
        startY    = 16;
        totHeight = 25;
    else
        startY    = 28.5;
        totHeight = 37.5;
    end

    start   = 4.5;
    width   = 25;
    height  = 7.5;
    ySpace  = height/1.8; 
    heightT = 2;

    % Create the main window
    %--------------------------------------------------------------
    if isa(parent,'nb_GUI')
        name = [parent.guiName ': Select Plot Type'];
    else
        name = 'Select Plot Type';
    end
    currentMonitor    = nb_getCurrentMonitor();
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    f    = figure('visible',        'off',...
                  'units',          'characters',...
                  'position',       [40, 15, start*5 + width*4, totHeight],...
                  'color',          defaultBackground,...
                  'name',           name,...
                  'numberTitle',    'off',...
                  'dockControls',   'off',...
                  'menuBar',        'None',...
                  'toolBar',        'None',...
                  'windowStyle',    'modal',...
                  'resize',         'off');                
    nb_moveFigureToMonitor(f,currentMonitor,'center');
    
    % Import the picture to add to the line button
    x = imread('line.png');

    uicontrol(f,...
              'units',          'characters',...
              'position',       [start,startY,width,height],...
              'callback',       callback,...
              'String',         '',...
              'cData',          x,...
              'Interruptible',  'off',...
              'Style',          'pushbutton',...
              'tag',            'line');

    uicontrol(f,...
              'units',       'characters',...
              'position',    [start,startY - heightT,width,heightT],...
              'String',      'Line',...
              'Style',       'text');      

    % Import the picture to add to the grouped bar button
    x = imread('grouped.png');

    uicontrol(f,...
              'units',          'characters',...
              'position',       [start*2 + width,startY,width,height],...
              'callback',       callback,...
              'String',         '',...
              'cData',          x,...
              'Interruptible',  'off',...
              'Style',          'pushbutton',...
              'tag',            'grouped');  

    uicontrol(f,...
              'units',       'characters',...
              'position',    [start*2 + width,startY - heightT,width,heightT],...
              'String',      'Grouped Bar',...
              'Style',       'text');          

    % Import the picture to add to the stacked bar button      
    x = imread('stacked.png');

    uicontrol(f,...
              'units',          'characters',...
              'position',       [start*3 + width*2,startY,width,height],...
              'callback',       callback,...
              'String',         '',...
              'cData',          x,...
              'Interruptible',  'off',...
              'Style',          'pushbutton',...
              'tag',            'stacked'); 

    uicontrol(f,...
              'units',       'characters',...
              'position',    [start*3 + width*2,startY - heightT,width,heightT],...
              'String',      'Stacked Bar',...
              'Style',       'text');          

    % Import the picture to add to the area button      
    x = imread('area.png');

    uicontrol(f,...
              'units',          'characters',...
              'position',       [start*4 + width*3,startY,width,height],...
              'callback',       callback,...
              'String',         '',...
              'cData',          x,...
              'Interruptible',  'off',...
              'Style',          'pushbutton',...
              'tag',            'area');           

    uicontrol(f,...
              'units',       'characters',...
              'position',    [start*4 + width*3,startY - heightT,width,heightT],...
              'String',      'Area',...
              'Style',       'text');            

     
    graphMethod = get(plotterT,'graphMethod');
    if strcmpi(graphMethod,'graph')
    
        % Import the picture to add to the dec bar button
        x = imread('dec.png');

        uicontrol(f,...
                  'units',          'characters',...
                  'position',       [start,startY - height - ySpace,width,height],...
                  'callback',       callback,...
                  'String',         '',...
                  'cData',          x,...
                  'Interruptible',  'off',...
                  'Style',          'pushbutton',...
                  'tag',            'dec');  

        uicontrol(f,...
                  'units',       'characters',...
                  'position',    [start,startY - height - ySpace - heightT,width,heightT],...
                  'String',      'Decomposed Bar',...
                  'Style',       'text');         
 
        if include
        
            % Import the picture to add to the scatter button      
            x = imread('scatter.png');

            uicontrol(f,...
                      'units',          'characters',...
                      'position',       [start*2 + width,startY - height - ySpace,width,height],...
                      'callback',       callback,...
                      'String',         '',...
                      'cData',          x,...
                      'Interruptible',  'off',...
                      'Style',          'pushbutton',...
                      'tag',            'scatter'); 

            uicontrol(f,...
                      'units',       'characters',...
                      'position',    [start*2 + width,startY - height - ySpace - heightT,width,heightT],...
                      'String',      'Scatter',...
                      'Style',       'text');         

            % Import the picture to add to the scatter button      
            x = imread('candle.png');

            uicontrol(f,...
                      'units',          'characters',...
                      'position',       [start*3 + width*2,startY - height - ySpace,width,height],...
                      'callback',       callback,...
                      'String',         '',...
                      'cData',          x,...
                      'Interruptible',  'off',...
                      'Style',          'pushbutton',...
                      'tag',            'candle');  

            uicontrol(f,...
                      'units',       'characters',...
                      'position',    [start*3 + width*2,startY - height - ySpace - heightT,width,heightT],...
                      'String',      'Candle',...
                      'Style',       'text');
                  
        end
              
    end

    if isa(plotterT,'nb_graph_cs') && strcmpi(graphMethod,'graph')
        
          
        % Import the picture to add to the pie button      
        x = imread('pie.png');

        uicontrol(f,...
                  'units',          'characters',...
                  'position',       [start*4 + width*3,startY - height - ySpace,width,height],...
                  'callback',       callback,...
                  'String',         '',...
                  'cData',          x,...
                  'Interruptible',  'off',...
                  'Style',          'pushbutton',...
                  'tag',            'pie');  

        uicontrol(f,...
                  'units',       'characters',...
                  'position',    [start*4 + width*3,startY - height - ySpace - heightT,width,heightT],...
                  'String',      'Pie',...
                  'Style',       'text');    
              
        % Import the picture to add to the donut button      
        x = imread('donut.png');

        uicontrol(f,...
                  'units',          'characters',...
                  'position',       [start,startY - height*2 - ySpace*2,width,height],...
                  'callback',       callback,...
                  'String',         '',...
                  'cData',          x,...
                  'Interruptible',  'off',...
                  'Style',          'pushbutton',...
                  'tag',            'donut');  

        uicontrol(f,...
                  'units',       'characters',...
                  'position',    [start,startY - height*2 - ySpace*2 - heightT,width,heightT],...
                  'String',      'Donut',...
                  'Style',       'text');             

        % Import the picture to add to the radar button      
        x = imread('radar.png');

        uicontrol(f,...
                  'units',          'characters',...
                  'position',       [start*2 + width,startY - height*2 - ySpace*2,width,height],...
                  'callback',       callback,...
                  'String',         '',...
                  'cData',          x,...
                  'Interruptible',  'off',...
                  'Style',          'pushbutton',...
                  'tag',            'radar');  

        uicontrol(f,...
                  'units',       'characters',...
                  'position',    [start*2 + width,startY - height*2 - ySpace*2 - heightT,width,heightT],...
                  'String',      'Radar',...
                  'Style',       'text');   
              
        % Import the picture to add to the image button      
        x = imread('image.png');

        uicontrol(f,...
                  'units',          'characters',...
                  'position',       [start*3 + width*2,startY - height*2 - ySpace*2,width,height],...
                  'callback',       callback,...
                  'String',         '',...
                  'cData',          x,...
                  'Interruptible',  'off',...
                  'Style',          'pushbutton',...
                  'tag',            'image');  

        uicontrol(f,...
                  'units',       'characters',...
                  'position',    [start*3 + width*2,startY - height*2 - ySpace*2 - heightT,width,heightT],...
                  'String',      'Image',...
                  'Style',       'text');  
              
    end
    
    % Make window visible
    %--------------------------------------------------------------      
    set(f,'visible','on');

end
