function fakeLegendPanel(gui)
% Syntax:
%
% fakeLegendPanel(gui)
%
% Description:
%
% Part of DAG. Creates a panel for editing fake legend properties
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2023, Kenneth Sæterhagen Paulsen

    % Create panel
    %--------------------------------------------------------------
    uip = uipanel('parent',              gui.figureHandle,...
                  'title',               '',...
                  'visible',             'off',...
                  'borderType',          'none',... 
                  'units',               'normalized',...
                  'position',            [0.22, 0.02, 1 - 0.24, 0.96]); 
    gui.panelHandle3 = uip;
    
    popWidth1 = 0.41;
    popHeight = 0.05;
    tHeight   = 0.04;
    startX    = 0.04;
    startY    = 0.85;

    % Select variable pop-up menu
    %------------------------------------------------------
    uicontrol('units',                  'normalized',...
              'position',               [startX, startY + popHeight, popWidth1, tHeight],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Select Fake Legend'); 

    if isempty(gui.plotter.fakeLegend)
        fakeLegends = {' '};
    else
        fakeLegends = gui.plotter.fakeLegend(1:2:end);
    end
    
    pop2 = uicontrol(...
              'units',          'normalized',...
              'position',       [startX, startY, popWidth1, popHeight],...
              'parent',         uip,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'string',         fakeLegends,...
              'Interruptible',  'off',...
              'value',          1,...
              'tag',         	'left',...
              'callback',       @gui.changeFakeLegend); 
    gui.popupmenu2 = pop2;
    
    % Add/delete fake legends
    %------------------------------------------------------
    bgWidth  = 0.2;
    bgHeight = popHeight;
    uicontrol(...
              'units',          'normalized',...
              'position',       [1 - popWidth1 - startX, startY, bgWidth, bgHeight],...
              'parent',         uip,...
              'style',          'pushbutton',...
              'string',         'Add',...
              'Interruptible',  'off',...
              'callback',       @gui.addFakeLegend); 

    uicontrol(...
              'units',          'normalized',...
              'position',       [1 - popWidth1 - startX, startY - tHeight*3, bgWidth, bgHeight],...
              'parent',         uip,...
              'style',          'pushbutton',...
              'string',         'Delete',...
              'Interruptible',  'off',...
              'callback',       @gui.deleteFakeLegend); 
            
    % Create the rest fake legend panel (Fake legend options)
    %--------------------------------------------------------------
    updateFakeLegendPanel(gui,fakeLegends{1},1);
      
end
