function makeGUI(gui)
% Syntax:
%
% makeGUI(gui)
%
% Description:
%
% Part of DAG.
% 
% Written by Kenneth Sæterhagen Paulsen
        
% Copyright (c) 2021, Kenneth Sæterhagen Paulsen

    % Create the main window
    %--------------------------------------------------------------
    parent           = gui.plotter.parent;
    f                = nb_guiFigure(parent,'Legend Properties',[40, 15, 85.5, 31.5],'normal');               
    gui.figureHandle = f;
    
    % Set up panel
    uib = uibuttongroup('parent',              f,...
                        'title',               '',...
                        'background',          [1 1 1],...
                        'Interruptible',       'off',...
                        'units',               'normalized',...
                        'position',            [0.02 0.02 0.18 0.96],...
                        'SelectionChangeFcn',  @gui.changePanel); 

                    
    if strcmpi(get(gui.plotter,'graphMethod'),'graphInfoStruct')
        
        uicontrol(...
            'units',       'normalized',...
            'position',    [0, 0.90, 1, 0.1],...
            'background',  [1 1 1],...   
            'parent',      uib,...
            'style',       'togglebutton',...
            'string',      'General'); 
        
        % Make sub-windows            
        generalPanel(gui);
        set(gui.panelHandle2,'visible','on');
        
    else
                    
        uicontrol(...
            'units',       'normalized',...
            'position',    [0, 0.90, 1, 0.1],...
            'background',  [1 1 1],...   
            'parent',      uib,...
            'style',       'togglebutton',...
            'string',      'Text'); 

        uicontrol(...
            'units',       'normalized',...
            'position',    [0, 0.80, 1, 0.1],...
            'background',  [1 1 1],...   
            'parent',      uib,...
            'style',       'togglebutton',...
            'string',      'General');             

        uicontrol(...
            'units',       'normalized',...
            'position',    [0, 0.70, 1, 0.1],...
            'background',  [1 1 1],...   
            'parent',      uib,...
            'style',       'togglebutton',...
            'string',      'Fake Legend'); 
        
        % Make sub-windows            
        textPanel(gui);
        generalPanel(gui);
        fakeLegendPanel(gui);
        
    end

    % Set the window visible            
    set(f,'visible','on');

end
