function s = struct(obj)
% Syntax:
%
% s = struct(obj)
%
% Description:
%
% Object to struct.
% 
% Input:
% 
% - obj : An nb_bd object.
% 
% Output:
% 
% - s  : A structure representing an nb_bd object.
%
% Written by Per Bjarne Bye

% Copyright (c) 2023, Kenneth Sæterhagen Paulsen

    s = struct('class',             'nb_bd',...
               'data',              obj.data,...
               'dataNames',         {obj.dataNames},...
               'frequency',         obj.frequency,...
               'localVariables',    obj.localVariables,...
               'startDate',         toString(obj.startDate),...
               'userData',          obj.userData,...
               'variables',         {obj.variables},...
               'links',             obj.links,...
               'sorted',            obj.sorted,...
               'updateable',        obj.updateable,...
               'locations',         obj.locations,...
               'indicator',         obj.indicator,...
               'ignorenan',         obj.ignorenan);

end
