function textPanel(gui)
% Creates a panel for editing general legend properties  

% Copyright (c) 2023, Kenneth Sæterhagen Paulsen

    % Get graph object 
    annh = gui.parent;

    % Create panel
    %--------------------------------------------------------------
    uip = uipanel('parent',              gui.figureHandle,...
                  'title',               '',...
                  'visible',             'on',...
                  'borderType',          'none',... 
                  'units',               'normalized',...
                  'position',            [0.22, 0.02, 1 - 0.24, 0.96]); 
    gui.panelHandle1 = uip;
    
    % Get the colors to choose from
    %--------------------------------------------------------------
    
    % Locate or give default color to the variable
    endc = gui.defaultColors;
  
    % Locate the selected face color in the color list
    colorTemp = annh.color;
    if ischar(colorTemp)
        colorTemp = nb_plotHandle.interpretColor(colorTemp);
    elseif iscell(colorTemp)
        colorTemp = nb_plotHandle.interpretColor(colorTemp);
    end

    [~,valueColor] = ismember(colorTemp,endc,'rows');
    if valueColor == 0
        endc              = [endc;colorTemp];
        valueColor        = size(endc,1);
        gui.defaultColors = endc;
    end
    
    % Using html coding to get the background of the 
    % listbox colored  
    colors = nb_htmlColors(endc);
    
    % Locations
    startPopX = 0.4;
    widthPop  = 0.35;
    heightPop = 0.055;
    startTX   = 0.04;
    widthT    = startPopX - startTX*2;
    heightT   = 0.053;
    widthB    = 1 - startPopX - widthPop - startTX*2;
    startB    = startPopX + widthPop + startTX;
    kk        = 9;
    spaceYPop = (1 - heightPop*kk)/(kk+1);
    extra     = -(heightPop - heightT)*5;
    
    % Text
    %--------------------------------------------------------------
%     uicontrol(...
%               'units',                  'normalized',...
%               'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
%               'parent',                 uip,...
%               'style',                  'text',...
%               'horizontalAlignment',    'left',...
%               'string',                 'Text');
%        
%     uicontrol(...
%               'units',          'normalized',...
%               'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
%               'parent',         uip,...
%               'background',     [1 1 1],...
%               'style',          'edit',...
%               'Interruptible',  'off',...
%               'string',         textBox.string,...
%               'callback',       {@gui.set,'string'});
    
    % Color
    %--------------------------------------------------------------
    %kk = kk - 1;
    uicontrol('units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Color'); 

    colmenu = uicontrol(...
              'units',          'normalized',...
              'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',         uip,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'Interruptible',  'off',...
              'tag',            'first',...
              'string',         colors,...
              'value',          valueColor,....
              'callback',       {@gui.set,'color'});

    coldef = uicontrol(...
              'units',          'normalized',...
              'position',       [startB, heightPop*(kk-1) + spaceYPop*kk, widthB, heightPop],...
              'parent',         uip,...
              'style',          'pushbutton',...
              'Interruptible',  'off',...
              'busyAction',     'cancel',...
              'string',         'Define');      
       
    set(coldef,'callback',{@nb_setDefinedColorAnnotation,gui,colmenu});      
              
    % Font Size
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Font Size');
    
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',                 uip,...
              'background',             [1 1 1],...
              'style',                  'edit',...
              'horizontalAlignment',    'right',...
              'Interruptible',          'off',...
              'string',                 num2str(annh.fontSize),...
              'callback',               {@gui.set,'fontSize'});
    
    % Font Weight
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Font Weight');

    weights = {'Normal','Bold','Light','Demi'};
    value   = find(strcmpi(annh.fontWeight,weights),1);

    uicontrol(...
              'units',          'normalized',...
              'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',          uip,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'Interruptible',  'off',...
              'string',         weights,...
              'value',          value,....
              'callback',       {@gui.set,'fontWeight'});
             
end
