function template = getExtendedTemplate()
% Syntax:
%
% template = nb_graph_package.getExtendedTemplate()
%
% Description:
%
% Get the template used for the extended format of the graphs.
% 
% See also:
% nb_graph_package.writeSeparateExtended, nb_graph_package.writePDFExtended
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    normalizeFactor = 0.002911226571376;
    template        = struct(...
        'addAdvanced',true,...
        'addExtraText',true,...
        'axesFontSize', 17*normalizeFactor,...
        'axesLineWidth', 0.5,...
        'barLineWidth', 1,...
        'baseLineWidth', 0.75,...
        'fanLegendFontSize', 12*normalizeFactor,...
        'figurePosition',[40,15,220,50],...
        'legBox', 'off',...
        'legColumns', 1,...
        'legFontSize', 14*normalizeFactor,...
        'legInterpreter', 'tex',...
        'legLocation','OutsideRightTop',...
        'legPosition',[],...
        'legSpace', 0.01,...
        'lineWidth', 2,...
        'markerSize', 5.5,...
        'normalized', 'axes',...
        'plotAspectRatio', '[4,3]',...
        'position',  [0.1, 0.5, 0.5, 0.3],...
        'position1', [0.1, 0.5, 0.225, 0.3],...
        'position2', [0.375, 0.5, 0.225, 0.3],...
        'shading', 'none',...
        'titleFontSize', 18*normalizeFactor,...
        'xLabelFontSize', 14*normalizeFactor,...
        'yLabelFontSize', 14*normalizeFactor,...
        'yOffset', 0.03...
    );

end
