function updateTypePanel(gui,variable,type)
% Syntax:
%
% updateTypePanel(gui,variable,type)
%
% Description:
%
% Part of DAG. Update the options panel  
% 
% Written by Kenneth Sæterhagen Paulsen    

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen

    % Get plotter object
    plotterT = gui.plotter;

    % Get the index of the variable choosen, and its options
    index   = find(strcmpi(variable,plotterT.nanVariables(1:2:end)),1);
    if ~isempty(index)
        options = plotterT.nanVariables{index*2}(2:end);
    end
    
    % Delete all old handles
    if ishandle(gui.editBox1)
        delete(gui.editBox1);
    end
    if ishandle(gui.editBox2)
        delete(gui.editBox2);
    end
    if ishandle(gui.listBox)
        delete(gui.listBox);
    end
    if ishandle(gui.textBox1)
        delete(gui.textBox1);
    end
    if ishandle(gui.textBox2)
        delete(gui.textBox2);
    end
    
    % Positions
    startPopX = 0.3;
    widthPop  = 0.35;
    heightPop = 0.09;
    startTX   = 0.04;
    widthT    = widthPop - startTX*2;
    heightT   = 0.06;
    kk        = 7;
    spaceYPop = (1 - heightPop*kk)/(kk + 1);
    extra     = (heightPop - heightT)/2; 

    kk = kk - 1;
    
    switch lower(type)
        
        case 'none'
            
            % Do nothing
            
        case 'before'
            
            % Update the GUI
            gui.textBox1 = uicontrol(...
                      'units',                  'normalized',...
                      'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
                      'parent',                 gui.panelHandle,...
                      'style',                  'text',...
                      'horizontalAlignment',    'left',...
                      'string',                 'Remove Before');
            
            gui.editBox1 = uicontrol(...
                  'units',                  'normalized',...
                  'position',               [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
                  'parent',                 gui.panelHandle,...
                  'background',             [1 1 1],...
                  'Interruptible',          'off',...
                  'horizontalAlignment',    'right',...
                  'style',                  'edit',...
                  'string',                 options{1},...
                  'callback',               @gui.setValue);       
                   
        case 'after'
            
            % Update the GUI
            gui.textBox1 = uicontrol(...
                      'units',                  'normalized',...
                      'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
                      'parent',                 gui.panelHandle,...
                      'style',                  'text',...
                      'horizontalAlignment',    'left',...
                      'string',                 'Remove After');
            
            gui.editBox1 = uicontrol(...
                  'units',                  'normalized',...
                  'position',               [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
                  'parent',                 gui.panelHandle,...
                  'background',             [1 1 1],...
                  'Interruptible',          'off',...
                  'horizontalAlignment',    'right',...
                  'style',                  'edit',...
                  'string',                 options{1},...
                  'callback',               @gui.setValue); 
            
            
        case 'beforeandafter'
            
            % Update the GUI
            
            % Before
            gui.textBox1 = uicontrol(...
                      'units',                  'normalized',...
                      'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
                      'parent',                 gui.panelHandle,...
                      'style',                  'text',...
                      'horizontalAlignment',    'left',...
                      'string',                 'Remove Before');
            
            gui.editBox1 = uicontrol(...
                  'units',                  'normalized',...
                  'position',               [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
                  'parent',                 gui.panelHandle,...
                  'background',             [1 1 1],...
                  'Interruptible',          'off',...
                  'horizontalAlignment',    'right',...
                  'style',                  'edit',...
                  'string',                 options{1},...
                  'callback',               @gui.setValue); 
              
            % After
            kk = kk - 1;
            gui.textBox2 = uicontrol(...
                      'units',                  'normalized',...
                      'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
                      'parent',                 gui.panelHandle,...
                      'style',                  'text',...
                      'horizontalAlignment',    'left',...
                      'string',                 'Remove After');
            
            gui.editBox2 = uicontrol(...
                  'units',                  'normalized',...
                  'position',               [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
                  'parent',                 gui.panelHandle,...
                  'background',             [1 1 1],...
                  'Interruptible',          'off',...
                  'horizontalAlignment',    'right',...
                  'style',                  'edit',...
                  'string',                 options{2},...
                  'callback',               @gui.setValue); 
            
            
        case 'between'
            
            % Update the GUI
            
            % After
            gui.textBox1 = uicontrol(...
                      'units',                  'normalized',...
                      'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
                      'parent',                 gui.panelHandle,...
                      'style',                  'text',...
                      'horizontalAlignment',    'left',...
                      'string',                 'Remove After');
            
            gui.editBox1 = uicontrol(...
                  'units',                  'normalized',...
                  'position',               [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
                  'parent',                 gui.panelHandle,...
                  'background',             [1 1 1],...
                  'Interruptible',          'off',...
                  'horizontalAlignment',    'right',...
                  'style',                  'edit',...
                  'string',                 options{1},...
                  'callback',               @gui.setValue); 
              
            % But Before
            kk = kk - 1;
            gui.textBox2 = uicontrol(...
                      'units',                  'normalized',...
                      'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
                      'parent',                 gui.panelHandle,...
                      'style',                  'text',...
                      'horizontalAlignment',    'left',...
                      'string',                 'But Remove Before');
            
            gui.editBox2 = uicontrol(...
                  'units',                  'normalized',...
                  'position',               [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
                  'parent',                 gui.panelHandle,...
                  'background',             [1 1 1],...
                  'Interruptible',          'off',...
                  'horizontalAlignment',    'right',...
                  'style',                  'edit',...
                  'string',                 options{2},...
                  'callback',               @gui.setValue); 
            
            
        case 'ind'
            
            allDates      = nb_getDatesAndLocals(plotterT);
            selectedDates = options{1};
            [~,value]     = ismember(selectedDates,allDates);
            
            if isempty(value)
                value = 1;
            end
            
            % Select list of dates to remove
            gui.textBox1 = uicontrol(...
                      'units',                  'normalized',...
                      'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT + 0.2, heightT],...
                      'parent',                 gui.panelHandle,...
                      'style',                  'text',...
                      'horizontalAlignment',    'left',...
                      'string',                 'Select Dates to Remove');
            
            ySpace     = 0.04;      
            heightList = heightPop*(kk-1) + spaceYPop*kk - ySpace*2;
            gui.editBox1 = uicontrol(...
                  'units',                  'normalized',...
                  'position',               [startTX, ySpace, widthPop, heightList],...
                  'parent',                 gui.panelHandle,...
                  'background',             [1 1 1],...
                  'Interruptible',          'off',...
                  'horizontalAlignment',    'right',...
                  'style',                  'listbox',...
                  'string',                 allDates,...
                  'value',                  value,...
                  'max',                    length(allDates),...
                  'callback',               @gui.selectDates); 
                       
    end
                
end
