function makeGUI(gui)
% Syntax:
%
% makeGUI(gui)
%
% Description:
%
% Part of DAG.
% 
% Written by Kenneth Sæterhagen Paulsen
        
% Copyright (c) 2021, Kenneth Sæterhagen Paulsen

    % Test if the data of the graph contains any of the variables
    % which can be added default fans
    %--------------------------------------------------------------
    plotterT = gui.plotter;
    
    if and(isempty(get(plotterT,'fanData')),isempty(plotterT.fanVariables)) 
        nb_errorWindow('Cannot add fan legend when no fan chart has been plotted.')
        return
    end
    
    parent = gui.plotter.parent;

    % Create the main window
    %--------------------------------------------------------------
    if isa(parent,'nb_GUI')
        name = [parent.guiName ': Fan Legend Properties'];
    else
        name = 'Fan Legend Properties';
    end
    
    currentMonitor    = nb_getCurrentMonitor();
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    f    = figure('visible',        'off',...
                  'units',          'characters',...
                  'position',       [40   15  85.5   31.5],...
                  'Color',          defaultBackground,...
                  'name',           name,...
                  'numberTitle',    'off',...
                  'dockControls',   'off',...
                  'menuBar',        'None',...
                  'toolBar',        'None',...
                  'resize',         'off',...
                  'windowStyle',    'modal');               
    gui.figureHandle = f;
    nb_moveFigureToMonitor(f,currentMonitor,'center');
    
    
    startPopX = 0.3;
    widthPop  = 0.35;
    heightPop = 0.055;
    startTX   = 0.04;
    widthT    = widthPop - startTX*2;
    heightT   = 0.053;
    widthB    = 1 - startPopX - widthPop - startTX*2;
    startB    = startPopX + widthPop + startTX;
    kk        = 9;
    spaceYPop = (1 - heightPop*kk)/(kk +1);
    extra     = -(heightPop - heightT)*5;
    
    % Add/remove fan legend
    %--------------------------------------------------------------
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 f,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Fan Legend');

    uicontrol(...
              'units',                  'normalized',...
              'position',               [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',                 f,...
              'style',                  'radiobutton',...
              'horizontalAlignment',    'left',...
              'Interruptible',          'off',...
              'string',                 'on/off',...
              'value',                  plotterT.fanLegend,...
              'callback',               {@gui.set,'fanLegend'});
     
    % Location
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 f,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Location');
   
    options = {'Best','NorthWest','North','NorthEast','SouthEast','South','SouthWest','outside'};
    
    if ischar(plotterT.fanLegendLocation)
        value   = find(strcmpi(plotterT.fanLegendLocation,options),1);
        enable  = 'on';
        valueR  = 1;
    else
        value   = 8;
        enable  = 'off';
        valueR  = 0;
    end
    
    pop1 = uicontrol(...
              'units',          'normalized',...
              'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',         f,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'Interruptible',  'off',...
              'string',         options,...
              'value',          value,....
              'enable',         enable,...
              'callback',       {@gui.set,'fanLegendLocation'}); 
    gui.popupmenu1 = pop1;      
          
    r1 = uicontrol(...
                  'units',          'normalized',...
                  'position',       [startB, heightPop*(kk-1) + spaceYPop*kk, widthB, heightPop],...
                  'parent',         f,...
                  'style',          'radiobutton',...
                  'Interruptible',  'off',...
                  'busyAction',     'cancel',...
                  'string',         'Loc/Pos',...
                  'value',          valueR,...
                  'callback',       {@gui.set,'switch'}); 
              
    gui.radiobutton1 = r1;      
              
    % Position
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 f,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Position');

    pos = plotterT.fanLegendLocation;
    if ischar(pos)
        pos1   = '';
        pos2   = '';
        enable = 'off';
    else
        pos1   = num2str(pos(1));
        pos2   = num2str(pos(2));
        enable = 'on';
    end
    
    space    = 0.05;
    widthPos = widthPop/2 - space/2;
    
    ed = uicontrol(...
              'units',              'normalized',...
              'position',           [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPos, heightPop],...
              'parent',             f,...
              'background',         [1 1 1],...
              'style',              'edit',...
              'Interruptible',      'off',...
              'horizontalAlignment','right',...
              'enable',             enable,...
              'string',             pos1,...
              'callback',           {@gui.set,'fanLegendLocation1'}); 
    gui.editbox1 = ed;
          
    ed = uicontrol(...
              'units',              'normalized',...
              'position',           [startPopX + widthPos + space, heightPop*(kk-1) + spaceYPop*kk, widthPos, heightPop],...
              'parent',             f,...
              'background',         [1 1 1],...
              'style',              'edit',...
              'Interruptible',      'off',...
              'horizontalAlignment','right',...
              'enable',             enable,...
              'string',             pos2,...
              'callback',           {@gui.set,'fanLegendLocation2'});  
    gui.editbox2 = ed;
    
    % Set the window visible   
    %--------------------------------------------------------------
    set(f,'visible','on');

end


