function template = getDefaultTemplate()
% Syntax:
%
% template = nb_graph.getDefaultTemplate()
%
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen 

    template = struct(...
        'addAdvanced',true,...
        'axesFontSize', 12,...
        'axesLineWidth', 0.5,...
        'barLineWidth', 1,...
        'baseLineWidth', 0.75,...
        'fanLegendFontSize', 12,...
        'figurePosition',[40,15,186.4,43],...
        'legBox', 'off',...
        'legColumns', 1,...
        'legFontSize', 10,...
        'legInterpreter', 'tex',...
        'legLocation','best',...
        'legPosition',[],...
        'legSpace', 0.01,...
        'lineWidth', 2,...
        'markerSize', 8,...
        'position',[0.1,0.1,0.8,0.8],...
        'position1',[0.1,0.1,0.8,0.8],...
        'position2',[0.1,0.1,0.8,0.8],...
        'plotAspectRatio','',...
        'titleFontSize', 14,...
        'xLabelFontSize', 12,...
        'yLabelFontSize', 12 ...
    );

end
