function options = getGenericOptions(obj)
% Syntax:
%
% options = getGenericOptions(obj)
%
% Description:
%
% A static method of nb_graph.
%
% Container with the intersect of options for subclasses of nb_graph.
%
% Input:
% 
% - none
%
% Output:
% 
% - options : A numSettings x 4 cell array with names in first column, 
%             default inputs in second, logical checks in the third, and
%             a function handle with the set function in the fourth. 
%
% Examples:
%
% options = getGenericOptions(obj);
%
% See also:
% set, nb_parseInputs
%
% Written by Per Bjarne Bye  

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen

    % Some sets for ismember checks________________________________
    
    align        = {'center','left','right'};
    cardinals    = {'north','south','west','east'};
    defaultPos   = [0.1 0.1 0.8 0.8];
    fontWeights  = {'normal','bold','light','demi'};
    fPerc        = [.3 .5 .7 .9];
    interpreters = {'latex','tex','none'};
    labelloc     = {'bottom','top','baseline'};
    linestyles   = {'-', '--','---',':','-.','none'};
    gridstyles   = {'-', '--',':','-.'};
    placement    = {'center','left','right','leftaxes'};
    
    % ///////////////////////////////////////////////////////////////////////////////// TABLE \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    %----------------------------------------------------------------------------------------------------------------------------------------------------------------
    %           PROPERTY NAME                          DEFAULT VALUE                         LOGICAL CHECKS                    FUNCTION HANDLE SETTING PROPERTY
    %----------------------------------------------------------------------------------------------------------------------------------------------------------------
    
    options = {'a4Portrait',               0,          @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'addAdvanced',              true,       @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'alignAxes',                [],         @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'annotation',               [],         {{@(x)isa(x,'nb_annotation')},'||',@iscell},                             @(name,value)setOnePropHandle(obj,name,value);...
               'addSpace',                 [0 0],      @isnumeric,                                                              @(name,value)setOnePropHandle(obj,name,value);...
               'areaAbrubt',               false,      @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'areaAccumulate',           true,       @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'areaAlpha',                1,          @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'axesFast',                 [],         @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'axesFontSize',             12,         @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'axesFontSizeX',            [],         {@nb_isScalarNumber,'||',@isempty},                                      @(name,value)setOnePropHandle(obj,name,value);...
               'axesFontWeight',           'normal',   {@ischar,'&&',@(x)nb_ismemberi(x,fontWeight)},                           @(name,value)setOnePropHandle(obj,name,value);...
               'axesLineWidth',            0.5,        @(x)nb_isScalarNumber(x,0),                                              @(name,value)setOnePropHandle(obj,name,value);...
               'axesPrecision',            [],         {@ischar,'||',@nb_isScalarInteger},                                      @(name,value)setOnePropHandle(obj,name,value);...
               'axesScaleFactor',          [],         {@isempty,'||',@nb_isScalarNumber},                                      @(name,value)setOnePropHandle(obj,name,value);...
               'axesScaleLineWidth',       false,      @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'barAlpha1',                0.5,        @(x)nb_isScalarNumber(x,0-eps,1+eps),                                    @(name,value)setOnePropHandle(obj,name,value);...
               'barAlpha2',                0.5,        @(x)nb_isScalarNumber(x,0-eps,1+eps),                                    @(name,value)setOnePropHandle(obj,name,value);...
               'barBlend',                 false,      @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'barLineWidth',             [],         {@isempty,'||',@(x)nb_isScalarInteger(x,0)},                             @(name,value)setOnePropHandle(obj,name,value);...
               'barShadingColor',          [1 1 1],    {@isnumeric,'||',@ischar,'||',@iscellstr},                               @(name,value)setOnePropHandle(obj,name,value);...
               'barShadingDirection',      'north',    {@ischar,'&&',@(x)nb_ismemberi(x,cardinals)},                            @(name,value)setOnePropHandle(obj,name,value);...
               'barWidth',                 0.45,       @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'baseLine',                 1,          @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'baseLineColor',            [0 0 0],    {@isnumeric,'||',@ischar,'||',@iscellstr},                               @(name,value)setOnePropHandle(obj,name,value);...
               'baseLineStyle',            '-',        {@ischar,'&&',@(x)ismember(x,linestyles)},                               @(name,value)setOnePropHandle(obj,name,value);...
               'baseLineWidth',            1,          @isscalar,                                                               @(name,value)setOnePropHandle(obj,name,value);...
               'baseValue',                0,          {@nb_isScalarNumber,'||',@nb_isOneLineChar},                             @(name,value)setOnePropHandle(obj,name,value);...
               'candleIndicatorColor',     [0 0 0],    {@isnumeric,'||',@ischar},                                               @(name,value)setOnePropHandle(obj,name,value);...
               'candleIndicatorLineStyle', '-',        @ischar,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'candleMarker',             'none',     @ischar,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'candleVariables',          {},         @iscellstr,                                                              @(name,value)setOnePropHandle(obj,name,value);...
               'candleWidth',              0.45,       @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'code',                     '',         @ischar,                                                                 @(name,value)setPropCode(obj,name,value);...
               'colorMap',                 [],         {@isnumeric,'||',@nb_isOneLineChar},                                     @(name,value)setOnePropHandle(obj,name,value);...
               'colorOrder',               [],         {@isnumeric,'||',@iscellstr},                                            @(name,value)setPropColorOrder(obj,name,value);...
               'colorOrderRight',          [],         {@isnumeric,'||',@iscellstr},                                            @(name,value)setPropColorOrder(obj,name,value);...
               'colors',                   {},         @iscell,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'crop',                     0,          @isscalar,                                                               @(name,value)setOnePropHandle(obj,name,value);...
               'factor',                   1,          @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'fakeLegend',               {},         @iscell,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'fanColor',                 'nb',       {@isnumeric,'||',@ischar},                                               @(name,value)setOnePropHandle(obj,name,value);... 
               'fanLegend',                0,          @isnumeric,                                                              @(name,value)setOnePropHandle(obj,name,value);...
               'fanLegendFontSize',        12,         @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'fanLegendLocation',        'outside',  {@isnumeric,'||',@ischar},                                               @(name,value)setOnePropHandle(obj,name,value);... 
               'fanLegendText',            {},         @iscell,                                                                 @(name,value)setOnePropHandle(obj,name,value);... 
               'fanPercentiles',           fPerc,      @isnumeric,                                                              @(name,value)setOnePropHandle(obj,name,value);...
               'figureColor',              [1 1 1],    {@isnumeric,'&&',@(x)nb_sizeEqual(x,[1,3])},                             @(name,value)setOnePropHandle(obj,name,value);...
               'figureHandle',             [],         {@(x)isa(x,'nb_figure')},                                                @(name,value)setPropFigureHandle(obj,name,value);...                                         
               'figurePosition',           [],         @isnumeric,                                                              @(name,value)setOnePropHandle(obj,name,value);...
               'figureName',               'none',     @ischar,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'figureTitle',              0,          {@nb_isScalarNumber,'||',@(x)ismember(x,[0,1]),'||',@nb_isOneLineChar},  @(name,value)setOnePropHandle(obj,name,value);...
               'fileFormat',               'pdf',      @ischar,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'findAxisLimitMethod',      4,          @(x)ismember(x,1:4),                                                     @(name,value)setOnePropHandle(obj,name,value);...
               'flip',                     0,          @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'fontName',                 'Arial',    @ischar,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'fontScale',                1,          @(x)nb_isScalarNumber(x,0),                                              @(name,value)setOnePropHandle(obj,name,value);...
               'fontUnits',                'points',   @ischar,                                                                 @(name,value)setPropFontUnits(obj,name,value);...
               'graphMethod',              '',         '',                                                                      @(name,value)setOnePropHandle(obj,name,value);...                                                                  
               'GraphStruct',              struct(),   {@ischar,'||',@isstruct},                                                @(name,value)setPropGraphStruct(obj,name,value);...
               'graphStyle',               'normal',   @ischar,                                                                 @(name,value)setPropGraphStyle(obj,name,value);...        
               'grid',                     'off',      @(x)nb_ismemberi(x,{'on','off'}),                                        @(name,value)setOnePropHandle(obj,name,value);...
               'gridLineStyle',            '--',       @(x)ismember(x,gridstyles),                                              @(name,value)setOnePropHandle(obj,name,value);...
               'highlight',                {},         @iscell,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'highlightColor',           {},         @iscell,                                                             	@(name,value)setOnePropHandle(obj,name,value);...
               'horizontalLine',           [],         @isnumeric,                                                              @(name,value)setOnePropHandle(obj,name,value);...
               'horizontalLineColor',      {},         {@iscell,'||',@ischar},                                                  @(name,value)setPropChar2Cellstr(obj,name,value);... 
               'horizontalLineStyle',      '-',        {@iscell,'||',@ischar},                                                  @(name,value)setPropChar2Cellstr(obj,name,value);...      
               'horizontalLineWidth',      1,          @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'language',                 'english',  @ischar,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'legAuto',                  'off',      @(x)nb_ismemberi(x,{'on','off'}),                                        @(name,value)setOnePropHandle(obj,name,value);...
               'legBox',                   'on',       @(x)nb_ismemberi(x,{'on','off'}),                                        @(name,value)setOnePropHandle(obj,name,value);...
               'legColor',                 'none',     '',                                                                      @(name,value)setPropLegColor(obj,name,value);...
               'legColumns',               1,          @(x)nb_isScalarNumber(x,0),                                              @(name,value)setOnePropHandle(obj,name,value);...
               'legColumnWidth',           [],         @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'legFontColor',             [0 0 0],    {@isnumeric,'||',@ischar,'||',@iscellstr},                               @(name,value)setOnePropHandle(obj,name,value);...
               'legFontSize',              10,         @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'legInterpreter',           'none',     {@ischar,'&&',@(x)nb_ismemberi(x,interpreters)},                         @(name,value)setOnePropHandle(obj,name,value);...
               'legLocation',              'Best',     @ischar,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'legPosition',              [],         {@isnumeric,'&&',@(x)nb_sizeEqual(x,[1,2])},                             @(name,value)setOnePropHandle(obj,name,value);...
               'legReorder',               'default',  {@isnumeric,'||',@ischar},                                               @(name,value)setOnePropHandle(obj,name,value);...
               'legSpace',                 0,          @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'legends',                  {},         {@iscell,'||',@ischar},                                                  @(name,value)setPropLegends(obj,name,value);...         
               'legendText',               {},         {@iscellstr,'&&',@(x)rem(size(x,2),2)==0},                               @(name,value)setPropLegendText(obj,name,value);...
               'lineStyles',               {},         @iscell,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'lineWidth',                0.25,       @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'lineWidths',               {},         @iscell,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'localVariables',           [],         @isstruct,                                                               @(name,value)setPropLocalVariables(obj,name,value);...
               'lookUpMatrix',             {},         {@ischar,'||',@iscell},                                                  @(name,value)setPropLookUpMatrix(obj,name,value);...                                                       
               'markers',                  {},         @iscell,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'markerSize',               8,          @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'noLegend',                 0,          @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'noLabel',                  0,          @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'noTickMarkLabels',         0,          @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'noTickMarkLabelsLeft',     0,          @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'noTickMarkLabelsRight',    0,          @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'normalized',               'figure',   @(x)nb_ismemberi(x,{'figure','axes'}),                                   @(name,value)setOnePropHandle(obj,name,value);...
               'noTitle',                  0,          @(x)ismember(x,0:2),                                                     @(name,value)setOnePropHandle(obj,name,value);...
               'page',                     [],         @isscalar,                                                               @(name,value)setPropPage(obj,name,value);...
               'parameters',               struct(),   @isstruct,                                                               @(name,value)setOnePropHandle(obj,name,value);...
               'patch',                    {},         @iscell,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'patchAlpha',               1,          @(x)nb_isScalarNumber(x,0-eps,1+eps),                                    @(name,value)setOnePropHandle(obj,name,value);...
               'pdfBook',                  0,          @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'plotAspectRatio',          [],         {@ischar,'||',@isempty},                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'plotType',                 'line',     @ischar,                                                                 @(name,value)setPropPlotType(obj,name,value);...                                                         
               'position',                 defaultPos, {@iscell,'||',@isnumeric,'&&',@(x)nb_sizeEqual(x,[1,4])},                @(name,value)setOnePropHandle(obj,name,value);...
               'saveName',                 '',         @ischar,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'scatterLineStyle',         'none',     @ischar,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'scatterVariables',         {},         @iscell,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'scatterVariablesRight',    {},         @iscell,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'shading',                  'none',     {@ischar,'||',@isnumeric},                                               @(name,value)setOnePropHandle(obj,name,value);...
               'subPlotSize',              [2 2],      {@isnumeric,'&&',@(x)nb_sizeEqual(x,[1,2])},                             @(name,value)setOnePropHandle(obj,name,value);...
               'subPlotSpecial',           0,          @(x)ismember(x,[0,1]),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'sumTo',                    [],         @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'title',                    '',         {@ischar,'||',@iscellstr},                                               @(name,value)setOnePropHandle(obj,name,value);...
               'titleAlignment',           'center',   @(x)nb_ismemberi(x,align),                                               @(name,value)setOnePropHandle(obj,name,value);...
               'titleFontSize',            14,         @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'titleFontWeight',          'bold',     @(x)nb_ismemberi(x,fontWeights),                                         @(name,value)setOnePropHandle(obj,name,value);...
               'titleInterpreter',         'none',     @(x)nb_ismemberi(x,interpreters),                                        @(name,value)setOnePropHandle(obj,name,value);...
               'titlePlacement',           'center',   @(x)nb_ismemberi(x,placement),                                           @(name,value)setOnePropHandle(obj,name,value);...
               'userData',                 '',         '',                                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'variablesToPlot',          {},         {@iscell,'||',@ischar},                                                  @(name,value)setPropChar2Cellstr(obj,name,value);...
               'variablesToPlotRight',     {},         {@iscell,'||',@ischar},                                                  @(name,value)setPropChar2Cellstr(obj,name,value);...
               'verticalLine',             {},         {@iscell,'||',@ischar,'||',@isnumeric},                                  @(name,value)setPropChar2Cellstr(obj,name,value);...
               'verticalLineColor',        {},         {@iscell,'||',@ischar},                                                  @(name,value)setPropChar2Cellstr(obj,name,value);...
               'verticalLineLimit',        {},         @iscell,                                                                 @(name,value)setOnePropHandle(obj,name,value);... 
               'verticalLineStyle',        {'--'},     {@iscell,'||',@ischar},                                                  @(name,value)setPropChar2Cellstr(obj,name,value);...
               'verticalLineWidth',        1.5,        @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'xLabel',                   '',         @ischar,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'xLabelAlignment',          'center',   @(x)ismember(x,align),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'xLabelFontSize',           12,         @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'xLabelFontWeight',         'bold',     @(x)nb_ismemberi(x,fontWeights),                                         @(name,value)setOnePropHandle(obj,name,value);...
               'xLabelInterpreter',        'none',     @(x)nb_ismemberi(x,interpreters),                                        @(name,value)setOnePropHandle(obj,name,value);...
               'xLabelPlacement',          'center',   @(x)nb_ismemberi(x,placement),                                           @(name,value)setOnePropHandle(obj,name,value);...
               'xLim',                     [],         {@isnumeric,'&&',@(x)nb_sizeEqual(x,[1,2]),'||',@isempty},               @(name,value)setOnePropHandle(obj,name,value);... 
               'xScale',                   'linear',   @(x)nb_ismemberi(x,{'linear','log'}),                                    @(name,value)setOnePropHandle(obj,name,value);...
               'xTickLabels',              {},         @iscell,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'xTickLabelLocation',       'bottom',   @(x)nb_ismemberi(x,labelloc),                                            @(name,value)setOnePropHandle(obj,name,value);...
               'xTickLocation',            'bottom',   {@(x)nb_ismemberi(x,{'bottom','top'}),'||',@nb_isScalarNumber},          @(name,value)setOnePropHandle(obj,name,value);...
               'xTickRotation',            0,          @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'yDir',                     'normal',   @(x)nb_ismemberi(x,{'normal','reverse'}),                                @(name,value)setOnePropHandle(obj,name,value);... 
               'yDirRight',                'normal',   @(x)nb_ismemberi(x,{'normal','reverse'}),                                @(name,value)setOnePropHandle(obj,name,value);... 
               'yLabel',                   '',         @ischar,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'yLabelFontSize',           12,         @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'yLabelFontWeight',         'bold',     @(x)nb_ismemberi(x,fontWeights),                                         @(name,value)setOnePropHandle(obj,name,value);...
               'yLabelInterpreter',        'none',     @(x)nb_ismemberi(x,interpreters),                                        @(name,value)setOnePropHandle(obj,name,value);...
               'yLabelRight',              '',         @ischar,                                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'yLim',                     [],         {@isnumeric,'&&',@(x)nb_sizeEqual(x,[1,2]),'||',@isempty},               @(name,value)setOnePropHandle(obj,name,value);...  
               'yLimRight',                [],         {@isnumeric,'&&',@(x)nb_sizeEqual(x,[1,2]),'||',@isempty},               @(name,value)setOnePropHandle(obj,name,value);... 
               'yOffset',                  0.01,       @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);... 
               'yScale',                   'linear',   @(x)nb_ismemberi(x,{'linear','log'}),                                    @(name,value)setOnePropHandle(obj,name,value);... 
               'yScaleRight',              'linear',   @(x)nb_ismemberi(x,{'linear','log'}),                                    @(name,value)setOnePropHandle(obj,name,value);... 
               'ySpacing',                 [],         @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'ySpacingRight',            [],         @nb_isScalarNumber,                                                      @(name,value)setOnePropHandle(obj,name,value)}; 

end
