function tempProps = getTemplateProps()
% Syntax:
%
% tempProps = nb_graph.getTemplateProps()
%
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen 

    tempProps = {...
        'addAdvanced',... 
        'axesFontSize',... 
        'axesLineWidth',... 
        'axesScaleLineWidth',...
        'axesScaleFactor',...
        'baseLineWidth',...  
        'fanLegendFontSize',...  
        'figurePosition',... 
        'legBox',... 
        'legColumns',... 
        'legFontSize',...
        'legInterpreter',...
        'legLocation',... 
        'legPosition',...
        'legSpace',... 
        'lineWidth',... 
        'markerSize',... 
        'noLegend',... 
        'position',...
        'position1',...
        'position2',...
        'plotAspectRatio',...   
        'titleFontSize',...
        'xLabelFontSize',...
        'yLabelFontSize',...
        'yLim'}; 
    
end
