function opt = optimset(varargin)
% Syntax:
%
% opt = nb_mcmc.optimset(varargin)
%
% Description:
%
% Default setting of the nb_mcmc.mhSampler and nb_mcmc.nutsampler. See 
% these function for help on the different fields (i.e. the optional 
% inputs).
% 
% Optional input:
%
% - varargin : Field name, field value pairs. These can be used to correct
%              the default values to your prefered choice.
%
% Output:
% 
% - opt : a struct with the default options of the sampler
%
% See also:
% nb_mcmc.mhSampler, nb_mcmc.nutsampler
%
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen

    [sampler,varargin] = nb_parseOneOptional('sampler','nb_mcmc.mhSampler',varargin{:});

    switch lower(sampler)
        
        case {'nb_mcmc.mhsampler','mhsampler'}
            
            opt = struct(...
            'accScale',0.1,...
            'accTarget',0.5,...
            'adaptive','recursive',... 
            'burn',4000,...
            'chains',1,...
            'covrepair','cov',...
            'draws',10000,...
            'lb',[],...
            'log',false,...
            'minIter',20,...
            'parallel',false,...
            'phi',[],...
            'qFunction','arw',...
            'qFuncPDF',[],...
            'sampler','nb_mcmc.mhSampler',...
            'storeAt',1000000,...
            'storeFile','mhSampler',...
            'thin',10,...
            'ub',[],...
            'waitbar',false,...
            'weight',0.05...
            );
        
        case {'nb_mcmc.nutsampler','nutsampler'}
            
            opt = struct(...
            'accTarget',0.8,...
            'burn',4000,...
            'chains',1,...
            'draws',10000,...
            'lb',[],...
            'log',false,...
            'maxTreeDepth',12,...
            'parallel',false,...
            'sampler','nb_mcmc.nutSampler',...
            'thin',10,...
            'ub',[],...
            'waitbar',false...
            );
        
        otherwise
            error([mfilename ':: Unsupported sampler ' sampler])
    end

    for ii = 1:2:length(varargin)
        
        if isfield(opt,varargin{ii})
            opt.(varargin{ii}) = varargin{ii+1};
        else
            error([mfilename ':: Unsupported option ''' varargin{ii} ''' for the sampler ' sampler '.'])
        end
        
    end

end
