function makeGUI(gui)
% Syntax:
%
% makeGUI(gui)
%
% Description:
%
% Part of DAG.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen

    % Get graph object 
    plotterAdv = gui.plotter;

    % Create window
    %--------------------------------------------------------------
    parent           = plotterAdv.plotter(1).parent;
    f                = nb_guiFigure(parent,'Round-off (graph specific)',[65   15  70   10],'normal');
    gui.figureHandle = f;
    
    startPopX = 0.4;
    widthPop  = 0.2;
    heightPop = 0.055*3;
    startTX   = 0.04;
    widthT    = startPopX - startTX*2;
    heightT   = 0.053*3;
    kk        = 2;
    spaceYPop = (1 - heightPop*kk)/(kk +1);
    extra     = -(heightPop - heightT)*5;
    
    % Number of decimals
    %--------------------------------------------------------------
    nb_uicontrolDAG(parent,...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 f,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Number of decimals',...
              'tooltip',                'Sets the number of decimals to be displayed in the Excel data sheet for this figure.');
          
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',                 f,...
              'style',                  'edit',...
              'Interruptible',          'off',...
              'backgroundColor',        [1,1,1],...
              'horizontalAlignment',    'right',...
              'string',                 int2str(plotterAdv.roundoff),...
              'callback',               @gui.setProperty);
          
    % Help text
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT*2.5, heightT + 0.1],...
              'parent',                 f,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 '*) Leave empty to use the round-off settings of the package');
 
    % Make GUI visible
    %--------------------------------------------------------------
    set(f,'visible','on')
          
end
