function setProps = set(obj,varargin)
% Syntax:
%
% set(obj, varargin)
%
% Description:
%
% Set properties of the nb_table_data_source class
% 
% Input:
% 
% - varargin : Property name property value pairs.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    oldFontUnits = obj.fontUnits;

    % Parse the arguments
    %--------------------------------------------------------------
    default = {'a4Portrait',            0,                  {{@ismember,[1,0]}};...
               'addAdvanced',           true,               @nb_isScalarLogical;...
               'annotation',            {},                 {{@isa,'nb_annotation'},'||',@iscell,'||',@isempty};...
               'columnSpan',            {},                 @iscell;...     
               'columnSizes',           [],                 @isnumeric;... 
               'crop',                  0,                  {{@ismember,[1,0]}};...
               'decimals',              4,                  {{@ismember,[0,1,2,3,4,5,6,7,8,9]},'||',@ischar};...
               'factor',                1,                  {@isnumeric,'&&',@isscalar};...
               'figureColor',           [1,1,1],            {@isnumeric,'&&',{@nb_sizeEqual,[1,3]}};...
               'figurePosition',        [],                 {@isnumeric,'&&',{@nb_sizeEqual,[1,4]},'||',@isempty};...
               'figureName',            '',                 {@ischar,'&&',{@nb_sizeEqual,[1,nan]},'||',@isempty};...
               'flip',                  0,                  {{@ismember,[1,0]}};...
               'fontName',              'Arial',            {@ischar,'&&',{@nb_sizeEqual,[1,nan]}};...
               'fontScale',             1,                  {@isnumeric,'&&',@isscalar,'&&',{@gt,0}};...
               'fontSize',              12,                 {@isnumeric,'&&',@isscalar,'&&',{@gt,0}};...
               'fontUnits',             'points',           {{@nb_ismemberi,{'normalized','inches','centimeters','points'}}};...
               'horizontalAlignment',	{},                 @iscell;...    
               'language',              'english',          {{@nb_ismemberi,{'english','norwegian'}}};...
               'localVariables',        [],                 {@isstruct,'||',@isempty};...
               'lookUpMatrix',          {},                 {@iscellstr,'&&',{@nb_sizeEqual,[nan,3]},'||',@isempty};...
               'noLabel',               0,                  {{@ismember,[1,0]}};...
               'normalized',            'figure',           {{@nb_ismemberi,{'figure','axes'}}};...
               'noTitle',               0,                  {{@ismember,[1,0]}};...
               'page',                  [],                 {@nb_iswholenumber,'&&',@isscalar,'||',@isempty};...
               'pdfBook',               0,                  {{@ismember,[1,0]}};...
               'plotAspectRatio',       {},                 {{@ismember,{'[4,3]','[16,9]'}},'||',@isempty};...
               'position',              [0.1 0.1 0.8 0.8],  {@isnumeric,'&&',{@nb_sizeEqual,[1,4]}};...
               'rowSpan',               {},                 @iscell;...    
               'saveName',              '',                 {@ischar,'||',@isempty};...
               'spacing',               1,                  {@nb_iswholenumber,'&&',{@gt,0}};...
               'tag',                   '',                 @ischar;...
               'title',                 '',                 {@ischar,'||',@isempty};...
               'titleAlignment',        'center',           {{@nb_ismemberi,{'center','left','right'}}};...
               'titleFontSize',         14,                 {@nb_iswholenumber,'&&',@isscalar};...
               'titleFontWeight',       'bold',             {{@nb_ismemberi,{'bold','normal','light','demi'}}};...
               'titleInterpreter',      'none',             {{@nb_ismemberi,{'latex','tex','none'}}};...
               'titlePlacement',        'center',           {{@nb_ismemberi,{'center','left','leftaxes','right'}}};...
               'xLabel',                '',                 {@ischar,'||',@isempty};...
               'xLabelAlignment',       'center',           {{@nb_ismemberi,{'center','left','right'}}};...
               'xLabelFontSize',        14,                 {@nb_iswholenumber,'&&',@isscalar};...
               'xLabelFontWeight',      'bold',             {{@nb_ismemberi,{'bold','normal','light','demi'}}};...
               'xLabelInterpreter',     'none',             {{@nb_ismemberi,{'latex','tex','none'}}};...
               'xLabelPlacement',       'center',           {{@nb_ismemberi,{'center','left','leftaxes','right'}}};...
               'userData',              '',                 {}};
           
    if isa(obj,'nb_table_ts')
        
        extra = {'datesOfTable',        {}, {@iscellstr,'||',@isempty};...
                 'endTable',            '', {{@nb_date.isDate,obj.DB.frequency,obj.localVariables}};...
                 'startTable',          '', {{@nb_date.isDate,obj.DB.frequency,obj.localVariables}};...
                 'variablesOfTable',    {}, {@iscellstr,'||',@isempty}};
        
    elseif isa(obj,'nb_table_cs')
        
        extra = {'typesOfTable',        [], {@iscellstr,'||',@isempty};...
                 'variablesOfTable',    {}, {@iscellstr,'||',@isempty}};
        
    elseif isa(obj,'nb_table_data')
        
        extra = {'observationsOfTable', [], {@isnumeric,'&&',{@nb_sizeEqual,[1,nan]},'||',@isempty};...
                 'endTable',            '', @nb_iswholenumber;...
                 'startTable',          '', @nb_iswholenumber;...
                 'variablesOfTable',    {}, {@iscellstr,'||',@isempty}};
        
    else 
        extra = cell(0,3);
    end
    default = [default;extra];
           
    [inputs,message,index] = nb_parseInputs(mfilename,default,varargin{:});
    if ~isempty(message)
        error(message)
    end
    
    propertyNames = fieldnames(inputs);
    setProps      = propertyNames(index);
    notSetProps   = propertyNames(~index);
    inputs        = rmfield(inputs,notSetProps);  
    if any(strcmpi('fontUnits',setProps)) 
        obj.fontUnits = inputs.fontUnits;
        setFontSize(obj,oldFontUnits);
    end 
    
    % Now its time to assign the changes
    for ii = 1:length(setProps)
        obj.(setProps{ii}) = inputs.(setProps{ii});
    end

end
