function s = struct(obj)
% Syntax:
%
% s = struct(obj)
%
% Description:
%
% Object to struct.
% 
% Input:
% 
% - obj : An nb_ts object.
% 
% Output:
% 
% - s  : A structure representing an nb_ts object.
%
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    s = struct('class',             'nb_ts',...
               'data',              obj.data,...
               'dataNames',         {obj.dataNames},...
               'endDate',           toString(obj.endDate),...
               'frequency',         obj.frequency,...
               'localVariables',    obj.localVariables,...
               'startDate',         toString(obj.startDate),...
               'userData',          obj.userData,...
               'variables',         {obj.variables},...
               'links',             obj.links,...
               'sorted',            obj.sorted,...
               'updateable',        obj.updateable);

end
