function textPanel(gui)
% Syntax:
%
% textPanel(gui)
%
% Description:
%
% Part of DAG.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2023, Kenneth Sæterhagen Paulsen

    % Get graph object 
    plotterT = gui.plotter;

    % Create panel
    %--------------------------------------------------------------
    uip = uipanel('parent',              gui.figureHandle,...
                  'title',               '',...
                  'visible',             'off',...
                  'borderType',          'none',... 
                  'units',               'normalized',...
                  'position',            [0.22, 0.02, 1 - 0.24, 0.96]); 
    gui.panelHandle3 = uip;
    
    startPopX = 0.3;
    widthPop  = 0.35;
    heightPop = 0.055;
    startTX   = 0.04;
    widthT    = widthPop - startTX*2;
    heightT   = 0.053;
    kk        = 9;
    spaceYPop = (1 - heightPop*kk)/(kk +1);
    extra     = -(heightPop - heightT)*5;
    
    
    % Font Name
    %--------------------------------------------------------------
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Font Name');

    options = listfonts;
    value   = find(strcmpi(plotterT.fontName,options),1);
    
    uicontrol(...
              'units',          'normalized',...
              'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',         uip,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'Interruptible',  'off',...
              'string',         options,...
              'value',          value,....
              'callback',       {@gui.set,'fontName'});
     
    kk = kk - 1;

    % Language
    %----------------------------------------------------------
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Language');


    strings = {'english','norwegian','engelsk','norsk'};
    lang    = plotterT.language; 
    value   = find(strcmpi(lang,strings));
    if isempty(value)
        value = 1;
    elseif value == 3
        value = 1;
    elseif value == 4
        value = 2;
    end
    strings = strings(1:2);

    uicontrol(...
              'units',          'normalized',...
              'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',         uip,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'Interruptible',  'off',...
              'string',         strings,...
              'value',          value,....
              'callback',       {@gui.set,'language'});  
          
    % Font Size Scalefactor
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Scale All Fonts');

    uicontrol(...
              'units',              'normalized',...
              'position',           [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',             uip,...
              'background',         [1 1 1],...
              'horizontalAlignment','right',...
              'style',              'edit',...
              'Interruptible',      'off',...
              'string',             num2str(plotterT.fontScale),...
              'callback',           {@gui.set,'fontScale'});   
      
    % Add some extra properties when the graph method 
    % 'graphInfoStruct' and 'graphSubPlots' are used      
    graphMethod = get(plotterT,'graphMethod');
    if ~strcmpi(graphMethod,'graph')
        
        % Axes Font Size
        %--------------------------------------------------------------
        kk = kk - 1;
        uicontrol(...
                  'units',                  'normalized',...
                  'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
                  'parent',                 uip,...
                  'style',                  'text',...
                  'horizontalAlignment',    'left',...
                  'string',                 'Axes Font Size');

        uicontrol(...
                  'units',              'normalized',...
                  'position',           [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
                  'parent',             uip,...
                  'background',         [1 1 1],...
                  'horizontalAlignment','right',...
                  'style',              'edit',...
                  'Interruptible',      'off',...
                  'string',             num2str(plotterT.axesFontSize),...
                  'callback',           {@gui.set,'axesFontSize'});
        
        % Title Font Size
        %--------------------------------------------------------------
        kk = kk - 1;
        uicontrol(...
                  'units',                  'normalized',...
                  'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
                  'parent',                 uip,...
                  'style',                  'text',...
                  'horizontalAlignment',    'left',...
                  'string',                 'Title Font Size');

        uicontrol(...
                  'units',              'normalized',...
                  'position',           [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
                  'parent',             uip,...
                  'background',         [1 1 1],...
                  'horizontalAlignment','right',...
                  'style',              'edit',...
                  'Interruptible',      'off',...
                  'string',             num2str(plotterT.titleFontSize),...
                  'callback',           {@gui.set,'titleFontSize'});
              
        % X-Axis Label Font Size
        %--------------------------------------------------------------
        kk = kk - 1;
        uicontrol(...
                  'units',                  'normalized',...
                  'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT - 0.02, heightT + 0.01],...
                  'parent',                 uip,...
                  'style',                  'text',...
                  'horizontalAlignment',    'left',...
                  'string',                 'X-Axis Label Font Size');

        uicontrol(...
                  'units',              'normalized',...
                  'position',           [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
                  'parent',             uip,...
                  'background',         [1 1 1],...
                  'horizontalAlignment','right',...
                  'style',              'edit',...
                  'Interruptible',      'off',...
                  'string',             num2str(plotterT.xLabelFontSize),...
                  'callback',           {@gui.set,'xLabelFontSize'});
              
        % Y-Axis Label Font Size
        %--------------------------------------------------------------
        kk = kk - 1;
        uicontrol(...
                  'units',                  'normalized',...
                  'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT - 0.02, heightT + 0.01],...
                  'parent',                 uip,...
                  'style',                  'text',...
                  'horizontalAlignment',    'left',...
                  'string',                 'Y-Axis Label Font Size');

        uicontrol(...
                  'units',              'normalized',...
                  'position',           [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
                  'parent',             uip,...
                  'background',         [1 1 1],...
                  'horizontalAlignment','right',...
                  'style',              'edit',...
                  'Interruptible',      'off',...
                  'string',             num2str(plotterT.yLabelFontSize),...
                  'callback',           {@gui.set,'yLabelFontSize'});
        
    end
    
    if strcmpi(graphMethod,'graphInfoStruct')
        
        % Figure title (on/off)
        %--------------------------------------------------------------
        kk = kk - 1;
        uicontrol(...
                  'units',                  'normalized',...
                  'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT - 0.02, heightT + 0.01],...
                  'parent',                 uip,...
                  'style',                  'text',...
                  'horizontalAlignment',    'left',...
                  'string',                 'Figure Title');

        uicontrol(...
                  'units',              'normalized',...
                  'position',           [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
                  'parent',             uip,...
                  'horizontalAlignment','right',...
                  'style',              'radiobutton',...
                  'Interruptible',      'off',...
                  'value',              plotterT.figureTitle,...
                  'callback',           {@gui.set,'figureTitle'});
         
    end
          
end
