function loadOptionsWhenExist(gui,updated)
% Syntax:
%
% loadOptionsWhenExist(gui,updated)
%
% Description:
%
% Part of DAG.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    % Create the window
    currentMonitor    = nb_getCurrentMonitor();
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    f = figure('Visible',     'off',...
               'units',       'characters',...
               'position',    [50 40 100 20],...
               'name',        [gui.parent.guiName ': Import Option'],...
               'NumberTitle', 'off',...
               'MenuBar',     'None',...
               'Toolbar',     'None',...
               'dockControls','off',...
               'resize',      'off',...
               'windowStyle', 'modal',...
               'Color',       defaultBackground);
    nb_moveFigureToMonitor(f,currentMonitor,'center');  
                       
    % Print question message

    message    = ['The graph(s) ' nb_cellstr2String(updated,', ',' and ') ' already exist(s), what do you want to do?'];
    uicontrol('parent',             f,...
              'units',              'normalized',...
              'position',           [0.04 0.25 0.96 0.4],...
              'Style',              'text',...
              'HorizontalAlignment','left',...
              'String',             message); 

    % Push buttons to give an answer
    %--------------------------------------------------------------
    bHeight = 0.1;
    bWidth  = 0.15;
    space   = 0.1;
    start   = (1 - bWidth*2 - space*1)/2;
    ySpace  = 0.1;

    uicontrol(f,...
                     'units',       'normalized',...
                     'position',    [start,ySpace,bWidth,bHeight],...
                     'callback',    @gui.exit,...
                     'String',      'Cancel',...
                     'Style',       'pushbutton');

    uicontrol(f,...
                     'units',       'normalized',...
                     'position',    [start + bWidth + space,ySpace,bWidth,bHeight],...
                     'callback',    @gui.overwrite,...
                     'String',      'Overwrite',...
                     'Style',       'pushbutton');
                             

    %Make the GUI visible.
    %--------------------------------------------------------------
    set(f,'Visible','on'); 
    gui.figureHandle = f;

end
