function options = getCSOptions(obj)
% Syntax:
%
% options = getCSOptions(obj)
%
% Description:
%
% A static method of nb_graph_cs.
%
% Container with the properties specific to nb_graph_cs
%
% Input:
% 
% - none
%
% Output:
% 
% - options : A numSettings x 4 cell array with names in first column, 
%             default inputs in second, logical checks in the third, and
%             function handles with the set function in the fourth.  
% Examples:
%
% options = getCSOptions(obj);
%
% See also:
% set, getGenericOptions, nb_parseInputs 
%
% Written by Per Bjarne Bye  

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    % Long default________________________________
    perc = 'percentiles';
    
    % Set for ismember check________________________________
    fanmethods = {'percentiles','hdi'};
    
    % ///////////////////////////////////////////////////////////////////////////////// TABLE \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    %----------------------------------------------------------------------------------------------------------------------------------------------------------------
    %           PROPERTY NAME                          DEFAULT VALUE                         LOGICAL CHECKS                    FUNCTION HANDLE SETTING PROPERTY
    %----------------------------------------------------------------------------------------------------------------------------------------------------------------
    
    options = {'barOrientation',        'vertical',         @ischar,                                                        @(name,value)setOnePropHandle(obj,name,value);...
               'barShadingTypes',       {},                 @iscellstr,                                                     @(name,value)setOnePropHandle(obj,name,value);...
               'donutInnerRadius',      -0.5,               @nb_isScalarNumber,                                             @(name,value)setOnePropHandle(obj,name,value);...
               'donutRadius',           1,                  @nb_isScalarNumber,                                             @(name,value)setOnePropHandle(obj,name,value);...
               'fanDatasets',           {},                 {@iscell,'||',{@isa,'nb_cs'},'||',@isstruct,'||',@isempty}, 	@(name,value)setOnePropHandle(obj,name,value);...
               'fanMethod',             perc,               @(x)nb_ismemberi(x,fanmethods),                                 @(name,value)setOnePropHandle(obj,name,value);... 
               'fanVariable',           '',                 @ischar,                                                        @(name,value)setOnePropHandle(obj,name,value);...
               'pieAxisVisible',        'on',               @(x)nb_ismemberi(x,{'on','off'}),                               @(name,value)setOnePropHandle(obj,name,value);...
               'pieEdgeColor',          [],                 {@nb_isColorProp,'||',@isempty},                                @(name,value)setOnePropHandle(obj,name,value);...
               'pieExplode',            {},                 @iscellstr,                                                     @(name,value)setOnePropHandle(obj,name,value);...
               'pieLabelsExtension',    '%',                @ischar,                                                        @(name,value)setOnePropHandle(obj,name,value);...
               'pieOrigoPosition',      [],                 {@isempty,'||',@isnumeric,'&&',@(x)nb_sizeEqual(x,[1,2])},      @(name,value)setOnePropHandle(obj,name,value);...
               'pieTextExplode',        {},                 @iscellstr,                                                     @(name,value)setOnePropHandle(obj,name,value);...
               'plotTypes',             {},                 @iscell,                                                        @(name,value)setOnePropHandle(obj,name,value);...
               'radarFontColor',        [0 0 0],            {@iscellstr,'||',@ischar,'||',@isnumeric},                      @(name,value)setOnePropHandle(obj,name,value);...
               'radarNumerOfIsoLines',  10,                 @nb_isScalarInteger,                                            @(name,value)setOnePropHandle(obj,name,value);...
               'radarRotate',           0,                  @nb_isScalarNumber,                                             @(name,value)setOnePropHandle(obj,name,value);...
               'radarScale',            [2,1.25],           {@isnumeric,'&&',@(x)nb_sizeEqual(x,[1,2])},                    @(name,value)setOnePropHandle(obj,name,value);...
               'scatterTypes',          {},                 @iscellstr,                                                     @(name,value)setOnePropHandle(obj,name,value);...
               'scatterTypesRight',     {},                 @iscellstr,                                                     @(name,value)setOnePropHandle(obj,name,value);...
               'typesToPlot',           {},                 {@iscell,'||',@ischar},                                         @(name,value)setPropChar2Cellstr(obj,name,value);...
               'typesToPlotRight',      {},                 {@iscell,'||',@ischar},                                         @(name,value)setPropChar2Cellstr(obj,name,value);...
               'xSpacing',              [],                 @nb_isScalarNumber,                                             @(name,value)setOnePropHandle(obj,name,value);...
               'xTickLabelAlignment',   'below',            @(x)nb_ismemberi(x,{'below','middle'}),                         @(name,value)setOnePropHandle(obj,name,value)};
           
end
