function options = getDataOptions(obj)
% Syntax:
%
% options = getDataOptions(obj)
%
% Description:
%
% Container with the properties specific to nb_graph_data
%
% Input:
% 
% - none
%
% Output:
% 
% - options : A numSettings x 4 cell array with names in first column, 
%             default inputs in second, logical checks in the third,
%             and a function handle with the set function in the fourth.
% Examples:
%
% options = getDataOptions(obj);
%
% See also:
% set, getGenericOptions, nb_parseInputs 
%
% Written by Per Bjarne Bye  

% Copyright (c) 2023, Kenneth Sæterhagen Paulsen
    
    % Set for ismember check________________________________
    fanmethods = {'percentiles','hdi'};
    
    % ///////////////////////////////////////////////////////////////////////////////// TABLE \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    %---------------------------------------------------------------------------------------------------------------------------------------------------------------------
    %           PROPERTY NAME                          DEFAULT VALUE                         LOGICAL CHECKS                               FUNCTION HANDLE SETTING PROPERTY
    %---------------------------------------------------------------------------------------------------------------------------------------------------------------------
    
    options = {'barPeriods',            [],                 @nb_iswholenumber,                                              @(name,value)setOnePropHandle(obj,name,value);... 
               'barShadingObs',         [],                 {@ischar,'||',@isnumeric,'||',@iscell},                         @(name,value)setOnePropHandle(obj,name,value);...
               'colorBarAtEnd',         'nb',               @nb_isOneLineChar,                                              @(name,value)setOnePropHandle(obj,name,value);...
               'dashedLine',            [],                 {@nb_ischar,'||',@isnumeric},                                   @(name,value)setOnePropHandle(obj,name,value);...
               'endBarWith',            3,                  @nb_isScalarInteger,                                            @(name,value)setOnePropHandle(obj,name,value);...
               'endGraph',              [],                 {@isnumeric,'||',@ischar},                                      @(name,value)setPropEndGraph(obj,name,value);...                               
               'fanDatasets',           {},                 {@iscell,'||',{@isa,'nb_data'},'||',@isstruct,'||',@isempty},   @(name,value)setOnePropHandle(obj,name,value);...
               'fanMethod',             'percentiles',      @(x)nb_ismemberi(x,fanmethods),                                 @(name,value)setOnePropHandle(obj,name,value);... 
               'fanVariable',           '',                 @ischar,                                                        @(name,value)setOnePropHandle(obj,name,value);...
               'lineStop',              [],                 @nb_isScalarInteger,                                            @(name,value)setOnePropHandle(obj,name,value);...
               'missingValues',         'none',             @(x)nb_ismemberi(x,{'none','interpolate'}),                     @(name,value)setOnePropHandle(obj,name,value);...
               'myLim',                 [],                 {@isempty,'||',@isnumeric,'&&',@(x)nb_sizeEqual(x,[1,2])},      @(name,value)setOnePropHandle(obj,name,value);...
               'nanAfterObs',           '',                 {@ischar,'||',@isnumeric},                                      @(name,value)setOnePropHandle(obj,name,value);...
               'nanBeforeObs',          '',                 {@ischar,'||',@isnumeric},                                      @(name,value)setOnePropHandle(obj,name,value);...
               'nanVariables',          {},                 @iscell,                                                        @(name,value)setOnePropHandle(obj,name,value);...
               'plotTypes',             {},                 @iscell,                                                        @(name,value)setOnePropHandle(obj,name,value);...
               'scatterObs',            {},                 {@iscell,'||',@ischar},                                         @(name,value)setPropChar2Cellstr(obj,name,value);...
               'scatterObsRight',       {},                 {@iscell,'||',@ischar},                                         @(name,value)setPropChar2Cellstr(obj,name,value);...
               'spacing',               [],                 @nb_isScalarNumber,                                             @(name,value)setOnePropHandle(obj,name,value);...
               'startGraph',            [],                 @isnumeric,                                                     @(name,value)setPropStartGraph(obj,name,value);...
               'variableToPlotX',       '',                 {@ischar,'||',@iscellstr},                                      @(name,value)setOnePropHandle(obj,name,value);...
               'xTickLabelAlignment',   'bottom',           @(x)nb_ismemberi(x,{'bottom','top','baseline'}),                @(name,value)setOnePropHandle(obj,name,value);...
               'xTickStart',            [],                 {@ischar,'||',@nb_isScalarNumber},                              @(name,value)setOnePropHandle(obj,name,value)};
           
end
