function options = getTSOptions(obj)
% Syntax:
%
% options = getTSOptions(obj)
%
% Description:
%
% Container with the properties specific to nb_graph_ts
%
% Input:
% 
% - none
%
% Output:
% 
% - options : A numSettings name 4 cell array with names in first column, 
%             default inputs in second, logical checks in the third,and
%             a function handle with the set function in the fourth. 
%
% Examples:
%
% options = getTSOptions(obj);
%
% See also:
% set, getGenericOptions, nb_parseInputs
%
% Written by Per Bjarne Bye  

% Copyright (c) 2023, Kenneth Sæterhagen Paulsen

    % Long default________________________________
    perc = 'percentiles';
    
    % Some sets for ismember checks________________________________
    fanmethods = {'percentiles','hdi','shaded','graded'};
    frequency  = {'annual','yearly','semiannually','quarterly','monthly','weekly','daily'};
    
    % ///////////////////////////////////////////////////////////////////////////////// TABLE \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
    %---------------------------------------------------------------------------------------------------------------------------------------------------------------------
    %           PROPERTY NAME                          DEFAULT VALUE                         LOGICAL CHECKS                               FUNCTION HANDLE SETTING PROPERTY
    %---------------------------------------------------------------------------------------------------------------------------------------------------------------------
    
    options = {'averageLine',              {},         @iscell,                                                                         @(name,value)setOnePropHandle(obj,name,value);...
               'barShadingDate',           nb_date,    {@ischar,'||',@(x)isa(x,'nb_date'),'||',@iscell},                                @(name,value)setPropBarShadingDate(obj,name,value);...                                            
               'dashedLine',               nb_date,    {@ischar,'||',@(x)isa(x,'nb_date')},                                             @(name,value)setPropDashedLine(obj,name,value);...                                       
               'dateInterpreter',          'start',    @ischar,                                                                         @(name,value)setOnePropHandle(obj,name,value);...
               'datesToPlot',              {},         {@iscell,'||',@ischar},                                                          @(name,value)setPropChar2Cellstr(obj,name,value);... 
               'defaultFans',              nb_date,    {@ischar,'||',@(x)isa(x,'nb_date')},                                             @(name,value)setPropDefaultFans(obj,name,value);...                                                            
               'endGraph',                 nb_date,    {@ischar,'||',@(x)isa(x,'nb_date')},                                             @(name,value)setPropEndGraph(obj,name,value);...
               'fanAlpha',                 1,          @(x)nb_isScalarNumber(x,0-eps,1+eps),                                            @(name,value)setOnePropHandle(obj,name,value);...
               'fanDatasets',              {},         {@iscell,'||',{@isa,'dyn_ts'},'||',{@isa,'nb_ts'},'||',@isstruct,'||',@isempty}, @(name,value)setOnePropHandle(obj,name,value);...
               'fanGradedLineWidth',       3,          @nb_isScalarNumber,                                                              @(name,value)setOnePropHandle(obj,name,value);...
               'fanGradedStyle',           'line',     @ischar,                                                                         @(name,value)setOnePropHandle(obj,name,value);...
               'fanFile',                  '',         @ischar,                                                                         @(name,value)setOnePropHandle(obj,name,value);...
               'fanMethod',                perc,       @(x)nb_ismemberi(x,fanmethods),                                                  @(name,value)setOnePropHandle(obj,name,value);... 
               'fanVariable',              '',         {@ischar,'||',@iscellstr},                                                       @(name,value)setOnePropHandle(obj,name,value);...
               'fanVariables',             {},         @iscellstr,                                                                      @(name,value)setOnePropHandle(obj,name,value);...
               'missingValues',            'none',     @ischar,                                                                         @(name,value)setOnePropHandle(obj,name,value);...
               'mYLim',                    [],         {@isempty,'||',@isnumeric,'&&',@(x)nb_sizeEqual(x,[1,2])},                       @(name,value)setOnePropHandle(obj,name,value);...
               'nanAfterDate',             '',         {@ischar, '||', @(x)isa(x,'nb_date')},                                           @(name,value)setPropNanDate(obj,name,value);...
               'nanBeforeDate',            '',         {@ischar, '||', @(x)isa(x,'nb_date')},                                           @(name,value)setPropNanDate(obj,name,value);...
               'nanVariables',             {},         @iscell,                                                                         @(name,value)setOnePropHandle(obj,name,value);...
               'plotTypes',                {},         @iscell,                                                                         @(name,value)setOnePropHandle(obj,name,value);...
               'scatterDates',             {},         {@iscell,'||',@ischar},                                                          @(name,value)setPropChar2Cellstr(obj,name,value);... 
               'scatterDatesRight',        {},         {@iscell,'||',@ischar},                                                          @(name,value)setPropChar2Cellstr(obj,name,value);... 
               'simpleRules',              {},         @iscell,                                                                         @(name,value)setOnePropHandle(obj,name,value);...
               'simpleRulesSecondData',    nb_ts,      {@ischar,'||',@(x)isa(x,'dyn_ts'),'||',@(x)isa(x,'nb_ts')},                      @(name,value)setPropSimpleRulesSecondData(obj,name,value);...                    
               'spacing',                  [],         @isscalar,                                                                       @(name,value)setOnePropHandle(obj,name,value);...
               'startGraph',               nb_date,    {@ischar,'||',@(x)isa(x,'nb_date')},                                             @(name,value)setPropStartGraph(obj,name,value);...                       
               'stopStrip',                '',         {{@isa,'nb_date'},'||',@ischar},                                                 @(name,value)setOnePropHandle(obj,name,value);...
               'stopUpdate',               nb_date,    {@isempty,'||',@ischar},                                                         @(name,value)setOnePropHandle(obj,name,value);...
               'subPlotsOptions',          struct(),   @isstruct,                                                                       @(name,value)setOnePropHandle(obj,name,value);...
               'xTickFrequency',           '',         @(x)nb_ismemberi(x,frequency),                                                   @(name,value)setOnePropHandle(obj,name,value);...
               'xTickLabelAlignment',      'normal',   @(x)nb_ismemberi(x,{'normal','middle'}),                                         @(name,value)setOnePropHandle(obj,name,value);...
               'xTickStart',               '',         @ischar,                                                                         @(name,value)setOnePropHandle(obj,name,value)};
           
end
