function makeGUI(gui)
% Syntax:
%
% makeGUI(gui)
%
% Description:
%
% Part of DAG.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2023, Kenneth Sæterhagen Paulsen

    % List of datasets
    appPackages  = gui.parent.graphPackages;
    packageNames = fieldnames(appPackages);

    if isempty(packageNames)
        nb_errorWindow('There are no stored graph package objects to load.')
        return
    end

    currentMonitor    = nb_getCurrentMonitor();
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    f = figure('visible',        'off',...
               'units',          'characters',...
               'position',       [65   15  70   30],...
               'Color',          defaultBackground,...
               'name',           [gui.parent.guiName ': Load Graph Package'],...
               'numberTitle',    'off',...
               'menuBar',        'None',...
               'toolBar',        'None',...
               'resize',         'off');
    nb_moveFigureToMonitor(f,currentMonitor,'center');
    
    % Panel with model selection list
    uip = uipanel('parent',              f,...
                  'title',               'Graph Package Objects',...
                  'units',               'normalized',...
                  'position',            [0.04, 0.04, 0.44, 0.92]);

    % List graph packages
    list = uicontrol('units',       'normalized',...
                     'position',    [0.02, 0.02, 0.96, 0.96],...
                     'parent',      uip,...
                     'background',  [1 1 1],...
                     'style',       'listbox',...
                     'string',      packageNames,...
                     'max',         1); 

    % Create load button
    width  = 0.2;
    height = 0.06;
    uicontrol('units',       'normalized',...
              'position',    [0.5 + 0.25 - width/2 - 0.01, 0.4, width, height],...
              'parent',      f,...
              'background',  defaultBackground,...
              'style',       'pushbutton',...
              'string',      'Load',...
              'callback',    @gui.selectPackage); 

    % Make it visible
    set(f,'visible','on')

    % Assign handles to the object
    gui.fig     = f;
    gui.listBox = list;

end
