function x = skt_mean(a,b,c,d)
% Syntax:
%
% x = nb_distribution.skt_mean(a,b,c,d)
%
% Description:
%
% Mean of the Azzalini skewed t-distribution.
% 
% Azzalini, A. and Capitanio,A. (2003). Distributions generated by 
% perturbation of symmetry with emphasis on a multivariate skew-t 
% distribution. J.Roy.Statist.Soc. B 65, 367-389.
% 
% Input:
% 
% - a : The location parameter (mean).
% 
% - b : The scale parameter.
%
% - c : The shape parameter.
%
% - d : Degrees of freedom (default is positive infinity which corresponds 
%       to the skew normal distribution)
%
% Output:
% 
% - x : The mean of the distribution
%
% See also:
% nb_distribution.skt_mode, nb_distribution.skt_median, 
% nb_distribution.skt_variance
%
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    if d > 1
        if d == inf
            delta = c/sqrt(1 + c^2);
            x     = a + b*delta*sqrt(2/pi);
        else
            delta = c/sqrt(1 + c^2);
            g2 = gamma(0.5*d);
            if g2 == inf
                delta = c/sqrt(1 + c^2);
                x     = a + b*delta*sqrt(2/pi);
            else
                g1    = gamma(0.5*(d - 1));
                mu = delta*sqrt(d/pi)*(g1/g2);
                x  = a + b*mu;
            end
        end
    else
        x = nan;
    end

end
