function f = skt_cdf(x,a,b,c,d)
% Syntax:
%
% f = nb_distribution.skt_cdf(x,a,b,c,d)
%
% Description:
%
% CDF of the Azzalini skewed t-distribution.
%
% Azzalini, A. and Capitanio,A. (2003). Distributions generated by 
% perturbation of symmetry with emphasis on a multivariate skew-t 
% distribution. J.Roy.Statist.Soc. B 65, 367-389.
% 
% Input:
% 
% - x : The point to evaluate the cdf, as a double.
%
% - a : The location parameter.
% 
% - b : The scale parameter.
%
% - c : The shape parameter.
%
% - d : Degrees of freedom (default is positive infinity which corresponds 
%       to the skew normal distribution)
%
% Output:
% 
% - f : The CDF at the evaluated points, same size as x.
%
% See also:
% nb_distribution.skt_pdf, nb_distribution.skt_rand,
% nb_distribution.skt_icdf, nb_mci
%
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    siz = size(x);
    x   = x';
    f   = azzalini.pskt(x,a,b,c,d);
    f   = reshape(f,siz);
    
end
