function domain = skt_domain(~,~,~,~,~)
% Syntax:
%
% f = nb_distribution.skt_domain
%
% Description:
%
% Get the domain of the Azzalini skewed t-distribution
%
% Azzalini, A. and Capitanio,A. (2003). Distributions generated by 
% perturbation of symmetry with emphasis on a multivariate skew-t 
% distribution. J.Roy.Statist.Soc. B 65, 367-389.
% 
% Output:
% 
% - domain : A 1x2 double with the lower and upper limits of the domain.
%
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2023, Kenneth Sæterhagen Paulsen

    domain = [-inf,inf];
    
end
