function draws = skt_rand(nrow,ncol,a,b,c,d)
% Syntax:
%
% draws = nb_distribution.skt_rand(nrow,ncol,a,b,c,d)
%
% Description:
%
% Draw random numbers from the Azzalini skewed t-distribution.
%
% Azzalini, A. and Capitanio,A. (2003). Distributions generated by 
% perturbation of symmetry with emphasis on a multivariate skew-t 
% distribution. J.Roy.Statist.Soc. B 65, 367-389.
% 
% Input:
% 
% - nrow  : Number of rows of the matrix drawn from the distribution
%
% - ncol  : Number of columns of the matrix drawn from the distrubution 
% 
% - a     : The location parameter.
% 
% - b     : The scale parameter.
%
% - c     : The shape parameter.
%
% - d     : Degrees of freedom (default is positive infinity which  
%           corresponds to the skew normal distribution)
%
% Output:
% 
% - draws : A nrow x ncol matrix of random numbers from the distribution  
%
% See also:
% nb_distribution.skt_pdf, nb_distribution.skt_cdf
%
% Modified by Kenneth S. Paulsen

% Copyright (c) 2023, Kenneth Sæterhagen Paulsen

    draws = azzalini.rskt(nrow*ncol,a,b,c,d);
    draws = reshape(draws,[nrow,ncol]);
    
end
    

