function x = skt_skewness(~,b,c,d)
% Syntax:
%
% x = nb_distribution.skt_skewness(a,b,c,d)
%
% Description:
%
% Skewness of the Azzalini skewed t-distribution.
% 
% Azzalini, A. and Capitanio,A. (2003). Distributions generated by 
% perturbation of symmetry with emphasis on a multivariate skew-t 
% distribution. J.Roy.Statist.Soc. B 65, 367-389.
% 
% Input:
% 
% - a : The location parameter.
% 
% - b : The scale parameter.
%
% - c : The shape parameter.
%
% - d : Degrees of freedom (default is positive infinity which corresponds 
%       to the skew normal distribution)
%
% Output:
% 
% - x : The skewness of the distribution
%
% See also:
% nb_distribution.skt_median, nb_distribution.skt_mean, 
% nb_distribution.skt_variance
%
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2023, Kenneth Sæterhagen Paulsen

    if d > 3
        if d == inf
            delta = c/sqrt(1 + c^2);
            x     = ((4 - pi)/2)*(((delta*sqrt(2/pi))^3)/((1 - (2*delta^2)/pi)^(3/2)) );
        else
            delta = b*c/sqrt(1 + b*c^2);
            g1    = gamma(0.5*(d - 1));
            if g1 == inf
                delta = c/sqrt(1 + c^2);
                x     = ((4 - pi)/2)*(((delta*sqrt(2/pi))^3)/((1 - (2*delta^2)/pi)^(3/2)) );
            else
                mu = delta*sqrt(d/pi)*(g1/gamma(0.5*d));
                k1 = (d*(3 - delta^2))/(d - 3);
                k2 = (3*d)/(d - 2);
                x  = mu*(k1 - k2 + 2*mu^2)*(( d/(d - 2) - mu^2)^(-3/2));
            end
        end
    else
        x = nan;
    end

end
