function nb_confirmWindow3(message,callbackfunc1,callbackfunc2,callbackfunc3,...
                          nameOfWindow,button1,button2,button3)
% Syntax:
%
% nb_confirmWindow3(message,callbackfunc1,callbackfunc2,callbackfunc3,...
%                           nameOfWindow,button1,button2,button3)
%
% Description:
%
% A window for printing confimation messages, with 3 options.
%
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen


    % Create the window
    currentMonitor    = nb_getCurrentMonitor();
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    f = figure('Visible',     'off',...
               'units',       'characters',...
               'position',    [50 40 100 20],...
               'name',        nameOfWindow,...
               'NumberTitle', 'off',...
               'MenuBar',     'None',...
               'Toolbar',     'None',...
               'resize',      'off',...
               'windowStyle', 'modal',...
               'Color',       defaultBackground);
    nb_moveFigureToMonitor(f,currentMonitor,'center');
    
    % Print question message
    uicontrol('parent',             f,...
              'units',              'normalized',...
              'position',           [0.04 0.25 0.96 0.4],...
              'Style',              'text',...
              'HorizontalAlignment','left',...
              'String',             message);

    % Push buttons to give an answer
    %--------------------------------------------------------------
    bHeight = 0.1;
    bWidth  = 0.15;
    space   = 0.1;
    ySpace  = 0.1;
    
    uicontrol(f,...
         'units',       'normalized',...
         'position',    [0.25 - bWidth/2,ySpace,bWidth,bHeight],...
         'callback',    callbackfunc1,...
         'String',      button1,...
         'Style',       'pushbutton');
    
    uicontrol(f,...
         'units',       'normalized',...
         'position',    [0.5 - bWidth/2,ySpace,bWidth,bHeight],...
         'callback',    callbackfunc2,...
         'String',      button2,...
         'Style',       'pushbutton'); 
     
    uicontrol(f,...
         'units',       'normalized',...
         'position',    [0.75 - bWidth/2,ySpace,bWidth,bHeight],...
         'callback',    callbackfunc3,...
         'String',      button3,...
         'Style',       'pushbutton');
                 
    %Make the GUI visible.
    %--------------------------------------------------------------
    set(f,'Visible','on');             
    
end
