function makeScatterGUI(gui)
% Syntax:
%
% makeScatterGUI(gui)
%
% Description:
%
% Part of DAG. Make GUI figure
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    plotter = gui.plotter;
    parent  = gui.plotter.parent;
    
    % Create the main window
    %--------------------------------------------------------------
    if isa(parent,'nb_GUI')
        name = [parent.guiName ': Select Variable'];
    else
        name = 'Select Variable';
    end
    
    currentMonitor    = nb_getCurrentMonitor();
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    f    = figure('visible',        'off',...
                  'units',          'characters',...
                  'position',       [40   15  85.5   31.5],...
                  'Color',          defaultBackground,...
                  'name',           name,...
                  'numberTitle',    'off',...
                  'dockControls',   'off',...
                  'menuBar',        'None',...
                  'toolBar',        'None',...
                  'resize',         'off',...
                  'windowStyle',    'modal');               
    nb_moveFigureToMonitor(f,currentMonitor,'center');
    
    popWidth1 = 0.41;
    popHeight = 0.05;
    tHeight   = 0.04;
    startX    = 0.04;
    startY    = 0.85;

    % Select variable pop-up menu
    %------------------------------------------------------
    uicontrol('units',                  'normalized',...
              'position',               [startX, startY + popHeight, popWidth1, tHeight],...
              'parent',                 f,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Select Scatter Group'); 

    if isa(plotter,'nb_graph_ts')      
        scatterGroups = plotter.scatterDates(1:2:end);
    elseif isa(plotter,'nb_graph_data')  
        scatterGroups = plotter.scatterObs(1:2:end);
    else
        scatterGroups = plotter.scatterVariables(1:2:end);
    end
    if isempty(scatterGroups)
        scatterGroups = {' '};
    end    
    pop1 = uicontrol(...
              'units',          'normalized',...
              'position',       [startX, startY, popWidth1, popHeight],...
              'parent',         f,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'Interruptible',  'off',...
              'string',         scatterGroups,...
              'value',          1,...
              'callback',       @gui.changeScatterGroup); 

    gui.figureHandle = f;
    gui.popupmenu1   = pop1;   

    % Select plot type pop-up menu
    %------------------------------------------------------
    uicontrol('units',                  'normalized',...
              'position',               [startX, startY - tHeight*2 + 0.007, popWidth1, tHeight],...
              'parent',                 f,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Select Axes'); 

    if ~isempty(gui.popupmenu2)
        delete(gui.popupmenu2);
    end

    pop2 = uicontrol(...
              'units',       'normalized',...
              'position',    [startX, startY - tHeight*3, popWidth1, popHeight],...
              'parent',      f,...
              'background',  [1 1 1],...
              'style',       'popupmenu',...
              'string',      {'Left','Right'},...
              'value',       1,....
              'callback',    @gui.scatterSelectSideToPlot); 
    gui.popupmenu2   = pop2;     
    
    % Create the rest of the GUI
    updateScatterGUI(gui,1);

    % Make the GUI visible.
    %------------------------------------------------------
    set(f,'Visible','on');

end
