function makeGUI(gui)
% Syntax:
%
% makeGUI(gui)
%
% Description:
%
% Part of DAG.
%
% Creates the menu for dates vs. dates plot.
% With a graph open: Properties > Special > Dates vs Dates.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen

    plotterT = gui.plotter;
    parent   = plotterT.parent;
    name     = 'Dates vs Dates Plot Options';

    % Create the main window
    %--------------------------------------------------------------
    f = nb_guiFigure(parent,name,[40   15  85.5   31.5],'modal','off');             
    gui.figureHandle = f;
    
    % Find the coordinate parameters
    %--------------------------------------------------------------
    popWidth1 = 0.41;
    popHeight = 0.05;
    tHeight   = 0.04;
    startX    = 0.04;
    startY    = 0.85;

    % Select if dates vs dates plot is wanted
    %--------------------------------------------------------------
    uicontrol('units',                  'normalized',...
              'position',               [startX, startY + tHeight, popWidth1, tHeight],...
              'parent',                 f,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Dates vs Dates Plot'); 

    value = ~isempty(plotterT.datesToPlot);      
          
    pop1 = uicontrol(...
              'units',          'normalized',...
              'position',       [startX*2 + popWidth1, startY + tHeight, popWidth1, popHeight],...
              'parent',         f,...
              'style',          'radiobutton',...
              'string',         '',...
              'Interruptible',  'off',...
              'value',          value,...
              'tag',         	'left',...
              'callback',       @gui.activateOptionsCallback); 
    gui.varpopup = pop1;
            
    % Create the options panel
    %--------------------------------------------------------------
    startX    = 0.04;
    startY    = 0.85;
    startYB   = 0.04;
    if value
        visible = 'on';
    else
        visible = 'off';
    end
    
    gui.panelHandle = uipanel(...
                      'parent',              gui.figureHandle,...
                      'visible',             visible,...
                      'title',               'Options',...
                      'units',               'normalized',...
                      'tag',                 'line',...
                      'position',            [startX, startYB, 0.92, startY - startYB]);

      
    % Positions
    heightPop = 0.08;
    startTX   = 0.04;
    widthList = (1 - startTX*3)/2;
    startTX2  = startTX*2 + widthList;
    heightT   = 0.07;
    kk        = 7;
    spaceYPop = (1 - heightPop*kk)/(kk + 1);
    extra     = (heightPop - heightT)/2; 

    allDates      = nb_getDatesAndLocals(plotterT.DB);
    selectedDates = plotterT.datesToPlot;
    [~,value]     = ismember(selectedDates,allDates);

    if isempty(value)
        value = 1;
    end

    % Select list of dates to plot
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthList, heightT],...
              'parent',                 gui.panelHandle,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Select Dates to Plot');

    ySpace     = 0.04;
    startList  = ySpace;%*2 + heightPop
    heightList = heightPop*(kk-1) + spaceYPop*kk - startList - ySpace;
    uicontrol(...
          'units',                  'normalized',...
          'position',               [startTX, startList, widthList, heightList],...
          'parent',                 gui.panelHandle,...
          'background',             [1 1 1],...
          'Interruptible',          'off',...
          'horizontalAlignment',    'right',...
          'style',                  'listbox',...
          'string',                 allDates,...
          'value',                  value,...
          'max',                    length(allDates),...
          'callback',               @gui.selectDates); 
      
    % Select list of variables to plot
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX2, heightPop*(kk-1) + spaceYPop*kk + extra, widthList, heightT],...
              'parent',                 gui.panelHandle,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Select Variables to Plot');

    selectedVariables = plotterT.variablesToPlot;
    [~,value]         = ismember(selectedVariables,plotterT.DB.variables);

    if isempty(value)
        value = 1;
    end      
          
    uicontrol(...
          'units',                  'normalized',...
          'position',               [startTX2, startList, widthList, heightList],...
          'parent',                 gui.panelHandle,...
          'background',             [1 1 1],...
          'Interruptible',          'off',...
          'horizontalAlignment',    'right',...
          'style',                  'listbox',...
          'string',                 plotterT.DB.variables,...
          'value',                  value,...
          'max',                    plotterT.DB.numberOfVariables,...
          'callback',               @gui.selectVariables);   
            
    % Plot options button  
%     uicontrol(...
%               'units',                  'normalized',...
%               'position',               [startTX, ySpace, widthList, heightPop],...
%               'parent',                 gui.panelHandle,...
%               'Interruptible',          'off',...
%               'horizontalAlignment',    'right',...
%               'style',                  'pushbutton',...
%               'string',                 'Plot Options',...
%               'callback',               @gui.optionsCallback); 
              
      
    % Make GUI visible 
    %--------------------------------------------------------------
    set(f,'visible','on');
          
end
