function addPanelFieldGUI(gui)
% Syntax:
%
% addPanelFieldGUI(gui)
%
% Description:
%
% Part of DAG.
% 
% Written by Per Bjarne Bye

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen
    
    f         = gui.figureHandle;
    sGraphObj = gui.infoStruct.(gui.name);
    
    % Position helpers
    startT2      = 0.53;
    startOp2     = 0.72;
    startDistBot = 0.97;
    numOp        = 0.05;
    heightT      = 0.053;
    heightEB     = 0.025;
    widthEB      = 0.26;
    delta        = 0.025;
    
    % Add panel-titles
    gui.uiText1 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startT2, startDistBot-numOp, 0.1, heightT],...
          'parent',                 f,...
          'style',                  'text',...
          'horizontalAlignment',    'left',...
          'fontWeight',             'bold',...
          'string',                 'Panel 1');
      
    gui.uiText2 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startT2, startDistBot-numOp*10, 0.1, heightT],...
          'parent',                 f,...
          'style',                  'text',...
          'horizontalAlignment',    'left',...
          'fontWeight',             'bold',...
          'string',                 'Panel 2');
          
    
    % Norwegian Excel Title _Plotter(2)
    gui.uiText3 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startT2, startDistBot-numOp*10.5, 0.35, heightT],...
          'parent',                 f,...
          'style',                  'text',...
          'horizontalAlignment',    'left',...
          'string',                 'Norwegian Excel Title');

    gui.editBox13 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startOp2, startDistBot-numOp*11.75+delta, widthEB, heightEB * 3.5],...
          'parent',                 f,...
          'style',                  'edit',...
          'horizontalAlignment',    'left',...
          'max',                    2,... 
          'string',                 sGraphObj.excelTitleNor_2); 

    % English Excel Title _Plotter(2)
    gui.uiText4 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startT2, startDistBot-numOp*12.5, 0.35, heightT],...
          'parent',                 f,...
          'style',                  'text',...
          'horizontalAlignment',    'left',...
          'string',                 'English Excel Title');

    gui.editBox14 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startOp2, startDistBot-numOp*13.75+delta, widthEB, heightEB * 3.5],...
          'parent',                 f,...
          'style',                  'edit',...
          'horizontalAlignment',    'left',...
          'max',                    2,... 
          'string',                 sGraphObj.excelTitleEng_2);  

    % Norwegian Excel Footer _Plotter(2)
    gui.uiText5 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startT2, startDistBot-numOp*14.5, 0.35, heightT],...
          'parent',                 f,...
          'style',                  'text',...
          'horizontalAlignment',    'left',...
          'string',                 'Norwegian Excel Footer');

    gui.editBox15 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startOp2, startDistBot-numOp*15.75+delta, widthEB, heightEB * 3.5],...
          'parent',                 f,...
          'style',                  'edit',...
          'horizontalAlignment',    'left',...
          'max',                    2,... 
          'string',                 sGraphObj.excelFooterNor_2);    
  
    % English Excel Footer _Plotter(2)
    gui.uiText6 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startT2, startDistBot-numOp*16.5, 0.35, heightT],...
          'parent',                 f,...
          'style',                  'text',...
          'horizontalAlignment',    'left',...
          'string',                 'English Excel Footer');

    gui.editBox16 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startOp2, startDistBot-numOp*17.75+delta, widthEB, heightEB * 3.5],...
          'parent',                 f,...
          'style',                  'edit',...
          'horizontalAlignment',    'left',...
          'max',                    2,... 
          'string',                 sGraphObj.excelFooterEng_2);  
    
end
