function addSingleFieldGUI(gui)   
% Syntax:
%
% addSingleFieldGUI(gui)
%
% Description:
%
% Part of DAG.
% 
% Written by Per Bjarne Bye

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen
    
    f         = gui.figureHandle;
    sGraphObj = gui.infoStruct.(gui.name);
    
    % Position helpers
    startT2      = 0.53;
    startOp2     = 0.72;
    startDistBot = 0.97;
    numOp        = 0.05;
    heightT      = 0.053;
    heightEB     = 0.025;
    widthEB      = 0.26;
    delta        = 0.025;
    
    if sGraphObj.panel
        xlTitNor = sGraphObj.excelTitleNor_1;
        xlTitEng = sGraphObj.excelTitleEng_1;
        xlFotNor = sGraphObj.excelFooterNor_1;
        xlFotEng = sGraphObj.excelFooterEng_1;
    else
        xlTitNor = sGraphObj.excelTitleNor;
        xlTitEng = sGraphObj.excelTitleEng;
        xlFotNor = sGraphObj.excelFooterNor;
        xlFotEng = sGraphObj.excelFooterEng;
    end
    
    % Norwegian Excel Title
    uicontrol(...
          'units',                  'normalized',...
          'position',               [startT2, startDistBot-numOp*2, 0.35, heightT],...
          'parent',                 f,...
          'style',                  'text',...
          'horizontalAlignment',    'left',...
          'string',                 'Norwegian Excel Title');

    gui.editBox9 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startOp2, startDistBot-numOp*3.25+delta, widthEB, heightEB * 3.5],...
          'parent',                 f,...
          'style',                  'edit',...
          'horizontalAlignment',    'left',...
          'max',                    2,... 
          'string',                 xlTitNor);    

   % English Excel Title
    uicontrol(...
          'units',                  'normalized',...
          'position',               [startT2, startDistBot-numOp*4, 0.35, heightT],...
          'parent',                 f,...
          'style',                  'text',...
          'horizontalAlignment',    'left',...
          'string',                 'English Excel Title');

    gui.editBox10 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startOp2,startDistBot-numOp*5.25+delta, widthEB, heightEB * 3.5],...
          'parent',                 f,...
          'style',                  'edit',...
          'horizontalAlignment',    'left',...
          'max',                    2,... 
          'string',                 xlTitEng);  
      
    % Norwegian Excel Footer
    uicontrol(...
          'units',                  'normalized',...
          'position',               [startT2, startDistBot-numOp*6, 0.35, heightT],...
          'parent',                 f,...
          'style',                  'text',...
          'horizontalAlignment',    'left',...
          'string',                 'Norwegian Excel Footer');

    gui.editBox11 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startOp2, startDistBot-numOp*7.25+delta, widthEB, heightEB * 3.5],...
          'parent',                 f,...
          'style',                  'edit',...
          'horizontalAlignment',    'left',...
          'max',                    2,... 
          'string',                 xlFotNor);    

   % English Excel Footer
    uicontrol(...
          'units',                  'normalized',...
          'position',               [startT2, startDistBot-numOp*8, 0.35, heightT],...
          'parent',                 f,...
          'style',                  'text',...
          'horizontalAlignment',    'left',...
          'string',                 'English Excel Footer');

    gui.editBox12 = uicontrol(...
          'units',                  'normalized',...
          'position',               [startOp2, startDistBot-numOp*9.25+delta, widthEB, heightEB * 3.5],...
          'parent',                 f,...
          'style',                  'edit',...
          'horizontalAlignment',    'left',...
          'max',                    2,... 
          'string',                 xlFotEng);       
         
end
