function helpEditTextGUICallback(~,~,~)
% Syntax:
%
% helpEditTextGUICallback(~,~,~)
%
% Description:
%
% Part of DAG.
% 
% Written by Per Bjarne Bye

% Copyright (c) 2023, Kenneth Sæterhagen Paulsen
    
    nb_helpWindow(...
        {'Workflow',...
        sprintf(['This sub-GUI is intended to work as follows: \n',...
        '1) In a session with advanced graphs you can edit the text in this \n',...
        'GUI. "Update" saves the text to the window, but not to the session! \n',...
        'To save the changes to the session, click the "Save to session". \n',...
        '2) If you want others to edit the text while you work with the graphs \n',...
        'in the session, you can export the text to a .mat file. \n',...
        '3) To work on the exported file independently of the session, run \n',...
        'nb_editTextGUI() in the command window. This will open an import dialogue \n',...
        'where you can choose the .mat file you exported. Choosing the correct \n',...
        'file will open the editing window outside DAG. Notice that you cannot \n',...
        'save the changes to the session. Export the .mat file and import it to \n',...
        'the desired session to implement the changes made.']),...
        'Save to session',...
        sprintf(['If you opened the editTextGUI from DAG, you will be able to "Save to session". \n',...
        'This function saves any changes made and saved in the window (aka, must be \n ',...
        '"Updated") to the graphs and the graph packages.']),...
        'Export to .mat file',...
        sprintf('This exports the text information to a .mat file in a chosen destination.'),...
        'Import from .mat file',...
        sprintf(['This imports the text information from a .mat file. The file imported must match \n',...
        'the session you are importing into. If all (advanced) graphs in the DAG session are in the \n ',...
        'imported .mat file, the behavior is trivial, i.e. text of all graphs are updated. However, \n',...
        'if some graphs are in the DAG session, but cannot be found in the imported file the \n',...
        'information for those graph(s) are taken from the DAG session and added to the \n',...
        'editTextGUI. On the other hand, if there are graphs in the imported file which cannot be \n',...
        'found in the DAG session (for example, if they have been deleted in the mean time), the \n',...
        'information of these graphs will simply be ignored and not added to the session.'])});

    

end
