function makeGUI(gui)
% Syntax:
%
% makeGUI(gui)
%
% Description:
%
% Part of DAG.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen

    % Get the variables plotted
    %--------------------------------------------------------------
    plotterAdv = gui.plotter;
    plotterT   = plotterAdv.plotter;
    types       = getPlottedTypes(plotterT);
    
    % Get the variables which is already removed
    %--------------------------------------------------------------
    forecastTypes = plotterAdv.forecastTypes;
    if isempty(types)
        nb_errorWindow('It is not possible set forecast types when there are no types included in table/graph.')
        return
    end
    
    if isa(plotterT.parent,'nb_GUI')
        name = [plotterAdv.plotter.parent.guiName ': Forecast Types'];
    else
        name = 'Forecast Types';
    end
     
    % Crate window
    %--------------------------------------------------------------
    currentMonitor    = nb_getCurrentMonitor();
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    mm = figure('visible',        'off',...
                'units',          'characters',...
                'position',       [45   10  80   25],...
                'name',           name,...
                'numberTitle',    'off',...
                'menuBar',        'None',...
                'windowStyle',    'modal',...
                'toolBar',        'None',...
                'color',          defaultBackground);
    movegui(mm,'center');
    nb_moveFigureToMonitor(mm,currentMonitor);
    gui.figureHandle = mm;

    % Locations  
    %--------------------------------------------------------------
    ySpace       = 0.04;
    startList    = 0.04;
    vListHeight  = 1 - ySpace*4;
    startListX1  = 0.04;
    listWidth    = 0.4;
    startListX2  = 1 - startListX1 - listWidth;
    space        = startListX2 - startListX1 - listWidth;
    buttonSize   = 0.06;

    % Plotted types list
    %--------------------------------------------------------------
    uicontrol(...
                   'units',       'normalized',...
                   'position',    [startListX1, ySpace*2 + vListHeight, listWidth, 0.04],...
                   'parent',      mm,...
                   'style',       'text',...
                   'string',      'Types'); 

    gui.varList = uicontrol(...
                     'units',       'normalized',...
                     'position',    [startListX1, ySpace, listWidth, vListHeight],...
                     'parent',      mm,...
                     'background',  [1 1 1],...
                     'style',       'listbox',...
                     'string',      types,...
                     'max',         size(types,2)); 

    % Forecast types list 
    %--------------------------------------------------------------
    uicontrol(...
                   'units',       'normalized',...
                   'position',    [startListX2, ySpace*2 + vListHeight, listWidth, 0.04],...
                   'parent',      mm,...
                   'style',       'text',...
                   'string',      'Forecast types'); 

    gui.selList = uicontrol(...
                     'units',       'normalized',...
                     'position',    [startListX2, startList, listWidth, vListHeight],...
                     'parent',      mm,...
                     'background',  [1 1 1],...
                     'style',       'listbox',...
                     'string',      forecastTypes); 

    % Create add variable to selected button 
    %--------------------------------------------------------------
    posB1 = [startListX1 + listWidth + space/2 - buttonSize/2, startList + vListHeight/2 + vListHeight/10 - buttonSize/2, buttonSize, buttonSize];
    uicontrol(...
                   'units',       'normalized',...
                   'position',    posB1,...
                   'parent',      mm,...
                   'style',       'pushbutton',...
                   'string',      '>',...
                   'callback',    @gui.select); 

    %  Create remove variable to selected button
    posB2 = [startListX1 + listWidth + space/2 - buttonSize/2, startList + vListHeight/2 - vListHeight/10 - buttonSize/2, buttonSize, buttonSize];
    uicontrol(...
                   'units',       'normalized',...
                   'position',    posB2,...
                   'parent',      mm,...
                   'style',       'pushbutton',...
                   'string',      '<',...
                   'callback',    @gui.deSelect); 

    % Make GUI visible
    %--------------------------------------------------------------
    set(mm,'visible','on');
          
end
