function textPanel(gui)
% Creates a panel for editing general legend properties  

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    % Get graph object 
    obj = gui.parent;

    % Create panel
    %--------------------------------------------------------------
    uip = uipanel('parent',              gui.figureHandle,...
                  'title',               '',...
                  'visible',             'off',...
                  'borderType',          'none',... 
                  'units',               'normalized',...
                  'position',            [0.22, 0.02, 1 - 0.24, 0.96]); 
    gui.panelHandle2 = uip;
    
    startPopX = 0.4;
    widthPop  = 0.35;
    heightPop = 0.055;
    startTX   = 0.04;
    widthT    = startPopX - startTX*2;
    heightT   = 0.053;
    widthB    = 1 - startPopX - widthPop - startTX*2;
    startB    = startPopX + widthPop + startTX;
    kk        = 9;
    spaceYPop = (1 - heightPop*kk)/(kk+1);
    extra     = -(heightPop - heightT)*5;
    
    % Font Color
    %--------------------------------------------------------------
    uicontrol('units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Font Color'); 

    gui.colorpop1 = uicontrol(...
              'units',          'normalized',...
              'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',         uip,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'Interruptible',  'off',...
              'tag',            'first',...
              'string',         gui.colors,...
              'value',          gui.valueColorTC,....
              'callback',       {@gui.set,'textColor'});

    gui.colordef1 = uicontrol(...
              'units',          'normalized',...
              'position',       [startB, heightPop*(kk-1) + spaceYPop*kk, widthB, heightPop],...
              'parent',         uip,...
              'style',          'pushbutton',...
              'Interruptible',  'off',...
              'busyAction',     'cancel',...
              'string',         'Define');  
    
    % Font Size
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Font Size');
    
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',                 uip,...
              'background',             [1 1 1],...
              'style',                  'edit',...
              'horizontalAlignment',    'right',...
              'Interruptible',          'off',...
              'string',                 num2str(obj.fontSize),...
              'callback',               {@gui.set,'fontSize'});
    
    % Font Weight
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Font Weight');

    weights = {'Normal','Bold','Light','Demi'};
    value   = find(strcmpi(obj.fontWeight,weights),1);

    uicontrol(...
              'units',          'normalized',...
              'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',          uip,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'Interruptible',  'off',...
              'string',         weights,...
              'value',          value,....
              'callback',       {@gui.set,'fontWeight'});
          
    % Interpreter
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Interpreter');

    interpreters = {'Tex','None','Latex'};
    value   = find(strcmpi(obj.interpreter,interpreters),1);

    uicontrol(...
              'units',          'normalized',...
              'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',          uip,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'Interruptible',  'off',...
              'string',         interpreters,...
              'value',          value,....
              'callback',       {@gui.set,'interpreter'});
    
    % Horizontal Alignment
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Horizontal Alignment');

    alignments = {'Left','Center','Right'};
    value      = find(strcmpi(obj.horizontalAlignment,alignments),1);

    uicontrol(...
              'units',          'normalized',...
              'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',          uip,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'Interruptible',  'off',...
              'string',         alignments,...
              'value',          value,....
              'callback',       {@gui.set,'horizontalAlignment'});
          
    % Vertical Alignment
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Vertical Alignment');

    alignments = {'Middle','Top','Cap','Baseline','Bottom'};
    value      = find(strcmpi(obj.verticalAlignment,alignments),1);

    uicontrol(...
              'units',          'normalized',...
              'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',          uip,...
              'background',     [1 1 1],...
              'style',          'popupmenu',...
              'Interruptible',  'off',...
              'string',         alignments,...
              'value',          value,....
              'callback',       {@gui.set,'verticalAlignment'});
          
    % Side
    %--------------------------------------------------------------
%     kk = kk - 1;
%     uicontrol(...
%               'units',                  'normalized',...
%               'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
%               'parent',                 uip,...
%               'style',                  'text',...
%               'horizontalAlignment',    'left',...
%               'string',                 'Side');
% 
%     sides = {'Left','Right'};
%     value = find(strcmpi(obj.side,sides),1);
% 
%     if strcmpi(obj.units,'data')
%         enable = 'on';
%     else
%         enable = 'off';
%     end
%     
%     h = uicontrol(...
%               'units',          'normalized',...
%               'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
%               'parent',          uip,...
%               'background',     [1 1 1],...
%               'style',          'popupmenu',...
%               'Interruptible',  'off',...
%               'string',         sides,...
%               'enable',         enable,...
%               'value',          value,....
%               'callback',       {@gui.set,'side'});
%     gui.sideHandle = h;      
          
    % Units
    %--------------------------------------------------------------
%     kk = kk - 1;
%     uicontrol(...
%               'units',                  'normalized',...
%               'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
%               'parent',                 uip,...
%               'style',                  'text',...
%               'horizontalAlignment',    'left',...
%               'string',                 'Units');
% 
%     units = {'Data','Normalized'};
%     value = find(strcmpi(obj.units,units),1);
% 
%     uicontrol(...
%               'units',          'normalized',...
%               'position',       [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
%               'parent',          uip,...
%               'background',     [1 1 1],...
%               'style',          'popupmenu',...
%               'Interruptible',  'off',...
%               'string',         units,...
%               'value',          value,....
%               'callback',       {@gui.set,'units'});
    
    % Text Rotation
    %--------------------------------------------------------------
    kk = kk - 1;
    uicontrol(...
              'units',                  'normalized',...
              'position',               [startTX, heightPop*(kk-1) + spaceYPop*kk + extra, widthT, heightT],...
              'parent',                 uip,...
              'style',                  'text',...
              'horizontalAlignment',    'left',...
              'string',                 'Text Rotation');

    uicontrol(...
              'units',                  'normalized',...
              'position',               [startPopX, heightPop*(kk-1) + spaceYPop*kk, widthPop, heightPop],...
              'parent',                 uip,...
              'background',             [1 1 1],...
              'style',                  'edit',...
              'horizontalAlignment',    'right',...
              'Interruptible',          'off',...
              'string',                 num2str(obj.textRotation),...
              'callback',               {@gui.set,'textRotation'});
    
          
end
