function makeGUI(gui)
% Syntax:
%
% makeGUI(gui)
%
% Description:
%
% Make GUI.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2021, Kenneth Sæterhagen Paulsen

    parent = gui.parent;

    % Create the main window
    %--------------------------------------------------------------
    if isa(parent,'nb_GUI')
        name = [parent.guiName ': ' gui.name];
    else
        name = gui.name;
    end
    
    if strcmpi('docked',get(0,'defaultFigureWindowStyle'))
        dockControls = 'on';
    else
        dockControls = 'off';
    end

    % Create the window
    currentMonitor    = nb_getCurrentMonitor();
    defaultBackground = get(0,'defaultUicontrolBackgroundColor');
    f = figure(  'Visible',     'off',...
                 'Color',       defaultBackground,...
                 'units',       'characters',...
                 'position',    [50 40 100 20],...
                 'name',        name,...
                 'NumberTitle', 'off',...
                 'MenuBar',     'None',...
                 'Toolbar',     'None',...
                 'resize',      'off',...
                 'tag',         'nb_waitbar5',...
                 'userData',    gui,...
                 'dockControls',dockControls);
    gui.figureHandle = f;         
    nb_moveFigureToMonitor(f,currentMonitor,'center');
    
    % Text boxes for messages
    tBoxes = nb_gobjects(1,5);
    for ii = 1:5
    	tBoxes(ii) = uicontrol(...
                      'parent',             f,...
                      'units',              'normal',...
                      'Style',              'text',...
                      'fontSize',           10,...
                      'String',             '',...
                      'visible',            'off');
    end
    gui.textBox = tBoxes;
    
    % Create a axes to "plot" the waiting bar on
    axHandles = nb_gobjects(1,5);
    for ii = 1:5
    	axHandles(ii) = axes(...
                     'parent',             f,...
                     'units',              'normal',...
                     'box',                'on',...
                     'yLim',               [0,1],...
                     'xLim',               [0,1],...
                     'xTick',              [],...
                     'yTick',              [],...
                     'visible',            'off');
    end
    gui.ax = axHandles;
    
    if gui.includeCancel && gui.includePause
        xc = 0.55;
        xp = 0.25;
    else
        xc = 0.4;
        xp = 0.4;
    end
    
    if gui.includeCancel
     
        gui.cancelButton = uicontrol(...
                  'parent',             f,...
                  'units',              'normal',...
                  'position',           [xc,0.1,0.2,0.1],...
                  'style',              'pushbutton',...
                  'string',             'Cancel',...
                  'callback',           @gui.cancelCallback); 
              
    end
    
    if gui.includePause
     
        gui.pauseButton = uicontrol(...
                  'parent',             f,...
                  'units',              'normal',...
                  'position',           [xp,0.1,0.2,0.1],...
                  'style',              'pushbutton',...
                  'string',             'Pause',...
                  'callback',           @gui.pauseCallback); 
              
    end
     
    % Make it visible
    set(f,'visible',gui.visible)

end
