function position = getCellPosition(obj, y, x, properties)

    indC     = min(x + properties.ColumnSpan - 1,length(obj.ColumnSizes));
    indR     = min(y + properties.RowSpan - 1,length(obj.RowSizes));
    position = [...
        sum(obj.ColumnSizes(1:(x - 1))), ...
        sum(obj.RowSizes(y + properties.RowSpan:end)), ...
        sum(obj.ColumnSizes(x:indC)), ...
        sum(obj.RowSizes(y:indR))];
end
