function patterns = stylingPatternsTemplate(name)
    
    patterns = struct(...
        'pattern', struct(), ...
        'direction', 'all', ...
        'startIndex', [1 1],...
        'template','');
    patterns(1) = [];
    
    switch lower(name)
        
        case 'demo'

            % Header
            patterns(end + 1).pattern = struct(...
                'BackgroundColor', [117 143 173] / 255, ...
                'Color', [1 1 1], ...
                'FontWeight', 'bold');
            patterns(end).direction = 'right';
            
            % Footer
            patterns(end + 1).pattern = struct(...
                'BackgroundColor', [117 143 173] / 255, ...
                'Color', [1 1 1], ...
                'FontWeight', 'bold');
            patterns(end).direction = 'right';
            patterns(end).startIndex = [0 1];
            
            % Odd columns
            patterns(end + 1).pattern = struct(...
                'BackgroundColor', {[227 230 231] / 255, []});
            
            % Odd rows
            patterns(end + 1).pattern = struct(...
                'BackgroundColor', {[227 230 231] / 255; []});
            
            % Default formatting
            patterns(end + 1).pattern = struct(...
                'HorizontalAlignment', 'left', ...
                'VerticalAlignment', 'middle', ...
                'Margin', 10, ...
                'BorderTop', 0, ...
                'BorderBottom', 0, ...
                'BorderLeft', 0, ...
                'BorderRight', 0);

        case 'nb'

            % Header
            patterns(end + 1).pattern = struct(...
                'BackgroundColor', [117 143 173] / 255, ...
                'Color', [1 1 1], ...
                'FontWeight', 'bold');
            patterns(end).direction = 'right';
            
            % Banded rows
            patterns(end + 1).pattern = struct(...
                'BackgroundColor', {[227 230 231] / 255; ...
                                    [1 1 1]});
                                
            % Default formatting
            patterns(end + 1).pattern = struct(...
                'HorizontalAlignment', 'left', ...
                'VerticalAlignment', 'middle', ...
                'Margin', 10, ...
                'BorderTop', 0, ...
                'BorderBottom', 0, ...
                'BorderLeft', 0, ...
                'BorderRight', 0);
            
        case 'latex'
            
            % Header
            patterns(end + 1).pattern = struct(...
                'BorderTop',  2, ...
                'BorderBottom', 1, ...
                'FontWeight', 'bold');
            patterns(end).direction = 'right';
                
            % Footer
            patterns(end + 1).pattern = struct(...
                'BorderTop',  1, ...
                'BorderBottom', 2);
            patterns(end).direction  = 'right';
            patterns(end).startIndex = [0,1];
            
            % Default formatting
            patterns(end + 1).pattern = struct(...
                'HorizontalAlignment', 'left', ...
                'VerticalAlignment', 'middle', ...
                'Margin', 10, ...
                'BorderTop', 1, ...
                'BorderBottom', 1, ...
                'BorderLeft', 0, ...
                'BorderRight', 0);

    end
    
    patterns(1).template = name;
    
end
