function makeGUI(gui)
% Syntax:
%
% makeGUI(gui)
%
% Description:
%
% Part of DAG.
% 
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    % Create the main window
    gui.components.figureHandle = nb_guiFigure([],'Define Color',...
        [40,15,55,11],'modal','off',@gui.close);               
    
    % Make the grid panel
%     numRows     = 11;
%     spaceWeight = 0.025;
%     uiWeight    = 
    gui.components.grid = nb_gridcontainer(gui.components.figureHandle,...
        'GridSize',[4,3],'Margin',15);
    
    % Get the colors to select from
    if isa(gui.parent,'nb_GUI')
        gui.colors = gui.parent.settings.defaultColors;
    else
        gui.colors = nb_defaultColors;
    end
    
    % Using html coding to get the background of the 
    % listbox colored  
    colors = nb_selectVariableGUI.htmlColors(gui.colors);

    % Select color 1
    uicontrol(gui.components.grid,...
        nb_constant.LABEL,...
        'String','Select color 1');
    gui.components.color1 = uicontrol(gui.components.grid,...
        nb_constant.POPUP,...
        'string',colors,...
        'value',1);
    uicontrol(gui.components.grid,...
        nb_constant.BUTTON,...
        'String','Add new color...',...
        'callback',@gui.defineCallback);
    
    % Select color 2
    uicontrol(gui.components.grid,...
        nb_constant.LABEL,...
        'String','Select color 2');
    gui.components.color2 = uicontrol(gui.components.grid,...
        nb_constant.POPUP,...
        'string',colors,...
        'value',1);
    uicontrol(gui.components.grid,...
        nb_constant.BUTTON,...
        'String','Add new color...',...
        'callback',@gui.defineCallback);
    
    % Alpha 1
    uicontrol(gui.components.grid,...
        nb_constant.LABEL,...
        'String','Alpha 1');
    gui.components.alpha1 = uicontrol(gui.components.grid,...
        nb_constant.EDIT,...
        'string','0.5');
    uicontrol(gui.components.grid,...
        nb_constant.BUTTON,...
        'String','Blend colors',...
        'callback',@gui.finishCallback);
    
    % Alpha 2
    uicontrol(gui.components.grid,...
        nb_constant.LABEL,...
        'String','Alpha 2');
    gui.components.alpha2 = uicontrol(gui.components.grid,...
        nb_constant.EDIT,...
        'string','0.5');
    nb_emptyCell(gui.components.grid);
    
    % Make figure visible
    set(gui.components.figureHandle,'visible','on');
      
end
