classdef nb_constant
% Description:
%
% UI controls settings.
%
% Written by Henrik Halvorsen Hortemo

% Copyright (c) 2023, Kenneth Sæterhagen Paulsen

    % UI Controls
    properties (Constant)
        LABEL = struct( ...
            'Style', 'text',  ...
            'Units', 'normalized',  ...
            'horizontalAlignment', 'left');

        EDIT = struct( ...
            'Style', 'edit', ...
            'Units', 'normalized', ...
            'Background', [1 1 1], ...
            'HorizontalAlignment', 'left', ...
            'Interruptible', 'off');

        POPUP = struct( ...
            'Style', 'popupmenu', ...
            'String', {' '}, ...
            'Units', 'normalized', ...
            'Background', [1 1 1], ...
            'HorizontalAlignment', 'right', ...
            'Interruptible', 'off');

        LISTBOX = struct( ...
            'Style', 'listbox', ...
            'Units', 'normalized', ...
            'Background', [1 1 1], ...
            'String', {' '}, ...
            'Max', 100);

        CHECKBOX = struct( ...
            'Units', 'normalized', ...
            'Style', 'checkbox', ...
            'Interruptible', 'off');
        
        RADIOBUTTON = struct(...
            'Style', 'radiobutton', ...
            'Units', 'normalized', ...
            'Interruptible', 'off');

        BUTTON = struct( ...
            'Style', 'pushbutton', ...
            'Units', 'normalized', ...
            'Interruptible', 'off', ...
            'BusyAction', 'cancel');
        
        TABLE = struct( ...
            'Units', 'normalized');
        
        BACKGROUNDCOLOR = get(0, 'defaultUicontrolBackgroundColor');
    end
    
    methods (Static)

    end
end
