function code = writeTex(obj,filename)
% Syntax:
%
% code = writeTex(obj,filename)
%
% Description:
%
% Write tex file of the equations.
% 
% Input:
% 
% - obj      : An object of class nb_eq2Latex.
%
% - filename : Give the name of the written .tex file. If not given or
%              empty no file will be written. Extension is ignored.
%
% Output:
% 
% - code : A Q x 1 cellstr with the latex code.
%
% Written by Kenneth Sæterhagen Paulsen

% Copyright (c) 2024, Kenneth Sæterhagen Paulsen

    if nargin < 2
        filename = '';
    end

    % Write preamble
    code     = cell(26,1);
    kk       = 1;
    code{kk} = '\\documentclass{article}\r\n';
    kk       = kk + 1;
    code{kk} = '\\usepackage{mathtools}\r\n';
    kk       = kk + 1;
    code{kk} = '\\usepackage{amsmath}\r\n';
    kk       = kk + 1;
    code{kk} = '\\usepackage{amssymb}\r\n';
    kk       = kk + 1;
    code{kk} = '\\usepackage{amsthm}\r\n';
    kk       = kk + 1;
    code{kk} = '\\usepackage{pifont}\r\n';
    kk       = kk + 1;
    code{kk} = '\\usepackage[latin1]{inputenc}\r\n';
    kk       = kk + 1;
    code{kk} = '\\usepackage[english]{babel}\r\n';
    kk       = kk + 1;
    code{kk} = '\\usepackage[T1]{fontenc}\r\n';
    kk       = kk + 1;
    code{kk} = '\\usepackage{setspace}\r\n';
    kk       = kk + 1;
    code{kk} = '\\usepackage{breqn}\r\n';
    kk       = kk + 1;
    code{kk} = '\\textheight=23cm\r\n';
    kk       = kk + 1;
    code{kk} = '\\textwidth=16.5cm\r\n';
    kk       = kk + 1;
    code{kk} = '\\oddsidemargin=0cm\r\n';
    kk       = kk + 1;
    code{kk} = '\\evensidemargin=0cm\r\n';
    kk       = kk + 1;
    code{kk} = '\\topmargin=-1.75cm\r\n';
    kk       = kk + 1;
    code{kk} = '\\renewcommand{\\baselinestretch}{1.15}\r\n';
    kk       = kk + 1;
    code{kk} = '\\newcommand{\\myparagraph}[1]{\\paragraph{#1}\\mbox{}\\\\}\r\n';
    kk       = kk + 1;
    code{kk} = '\\title{Generated by NB toolbox}\r\n';
    kk       = kk + 1;
    code{kk} = '\\date{\\today}\r\n';
    kk       = kk + 1;
    code{kk} = '\\begin{document}\r\n';
    kk       = kk + 1;
    code{kk} = '\\maketitle\r\n';
    kk       = kk + 1;
    code{kk} = '\\begin{abstract}\r\n';
    kk       = kk + 1;
    code{kk} = 'This is made in the hope that it is useful, but no guarantees can be given that it is correct.\r\n';
    kk       = kk + 1;
    code{kk} = '\\end{abstract}\r\n';
    kk       = kk + 1;
    code{kk} = '\\clearpage\r\n';
    
    % Write the tex equations
    obj     = obj(:); 
    nObj    = size(obj,1);
    eqsCode = cell(nObj*3,1);
    for ii = 1:nObj
        eqsCode{(ii - 1)*3 + 1} = '\\begin{dmath}\r\n';
        eqsCode{(ii - 1)*3 + 2} = [strrep(obj(ii).latex,'\','\\') '\r\n'];
        eqsCode{(ii - 1)*3 + 3} = '\\end{dmath}\r\n';
    end
    
    % End and concatenate
    code = [code;eqsCode;{'\\end{document}\r\n'}];
    
    % Write to file if asked for
    if ~isempty(filename)
        
        % Make it robust to the case where the extension is given.
        [path,filename] = fileparts(filename);
        if ~isempty(path)
            filename = [path,filesep,filename];
        end
        nb_cellstr2file(code,[filename,'.tex'],false);
        
    end
    
end
