%% Get help on this example

help nb_graph_adv
properties(nb_graph_adv)

help nb_graph_ts
properties(nb_graph_ts)

%% Adding figure titles and footers 
% to nb_graph_ts, nb_graph_data or nb_graph_cs objects

% Reading data from a excel spreadsheet
data = nb_ts('example_ts_quarterly_mat');

% Initialize an nb_graph_ts object with the above data
plotter = nb_graph_ts(data);

plotter.set('graphStyle',       'mpr',...
            'variablesToPlot',  {'Var1','Var2'},...
            'legends',          {'Første','Andre'},...
            'legPosition',      [0.1 0.7],...
            'yLim',             [0,1],...
            'ySpacing',         1 ...
            );

figureTitleNorwegian = {'En tittel til figuren',...
                        plotter.timespan('')};

footerNorwegian      = {'1) En fotnote.',...
                        'Kilde: En plass.'};

figureTitleEnglish   = {'A title for the graph',...
                        plotter.timespan('english')};
                    
% figureTitleEnglish   = {'A title for the graph which is very long and need to be broken at some point?',...
%                         plotter.timespan('english')};                    

footerEnglish        = {'1) A footnote.',...
                        'Source: From somewhere.'};
                    
% footerEnglish        = {'1) A footnote which is very long and boring. Should we maybe break it somewhere here?',...
%                         'Source: From somewhere.'};                    
              
legendsEng           =  {'First',...
                         'Second'};

plotterAdv = nb_graph_adv(plotter...
      ,'legendsEng',          legendsEng...
      ,'figureTitleEng',      figureTitleEnglish...
      ,'footerEng',           footerEnglish...
      ,'figureTitleNor',      figureTitleNorwegian...
      ,'footerNor',           footerNorwegian...
      ,'footerWrapping',      false...
      ,'figureTitleWrapping', false...
      ); 
                      
% Graph Norwegian version
plotterAdv.graphNor()

% Graph English version
plotterAdv.graphEng()

%% Advanced graph panel with two graphs

% Reading data from a excel spreadsheet
data = nb_ts('example_ts_quarterly_mat');

lookUp = {...
    'Leg1','First','Første'
    'Leg2','Second','Andre'
};

% Initialize an nb_graph_ts object with the above data
plotter1 = nb_graph_ts(data);

plotter1.set('graphStyle',       'mpr',...
            'variablesToPlot',  {'Var1','Var2'},...
            'legends',          {'Leg1','Leg2'},...
            'legPosition',      [0.1 0.7],...
            'position',         [0.15,0.25,0.25,0.5],...
            'lookUpMatrix',     lookUp,...
            'yLim',             [0,1],...
            'ySpacing',         1 ...
            );

% Initialize an nb_graph_ts object with the above data
plotter2 = nb_graph_ts(data);

plotter2.set('graphStyle',       'mpr',...
            'variablesToPlot',  {'Var1','Var2'},...
            'legends',          {'Leg1','Leg2'},...
            'legPosition',      [0.1 0.7],...
            'lookUpMatrix',     lookUp,...
            'position',         [0.6,0.25,0.25,0.5],...
            'yLim',             [0,1],...
            'ySpacing',         1 ...
            );

plotterAdv = nb_graph_adv(plotter1);
plotterAdv.addGraph(plotter2)

% Graph Norwegian version
plotterAdv.graphNor()

% Graph English version
plotterAdv.graphEng()
