%% Get help on this example

help nb_graph_package
properties(nb_graph_package)

%% Creating a graph package

graphNumber = 1;
chapter     = 1;

% Initialize a nb_graph_package object
package = nb_graph_package(graphNumber,chapter);

% Set the lookUpMatrix property of the package object
package = package.set('lookUpMatrix','lookUpMatrix_Package');

%% Setting up a graph and adding it to the graph package

% Reading data from a excel spreadsheet
data = nb_ts(rand(36,2),'','2008Q1',{'QUA_VAR1','QUA_VAR2'});

% Initialize an nb_graph_ts object with the above data
plotter = nb_graph_ts(data);

plotter.set('graphStyle',       'mpr',...
            'variablesToPlot',  {'QUA_VAR1','QUA_VAR2'},...
            'legends',          {'Variabel en','Variabel to'},...
            'lineStyles',       {'QUA_VAR1','--'},...
            'legPosition',      [0.1 0.7],...
            'yLim',             [0,8],...
            'ySpacing',         1 ...
            );

figureTitleNorwegian = {['Sammenligning av variabel en^{1)} '...
                        'og variabel to.'],...
                        plotter.timespan('')};

footerNorwegian      = {'1) Variabel en er ikke variabel to.',...
                        'Kilde: MATLAB'};

figureTitleEnglish   = {['Comparison of the first variable^{1)} '...
                        'and second variable.'],...
                        plotter.timespan('english')};

footerEnglish        = {['1) The first variable is not the '...
                        'second variable'],...
                        'Source: MATLAB'};
              
legendsEng           =  {'First variable',...
                         'Second variable'};

figureNameNor        = {'Eksempel 1'};

figureNameEng        = {'Example 1'};

forecastDate         = '2013Q3';                     
                     
plotterAdv = nb_graph_adv(plotter,...
                          'forecastDate',   forecastDate,...
                          'figureNameNor',  figureNameNor,...
                          'figureNameEng',  figureNameEng,...
                          'legendsEng',     legendsEng,...
                          'figureTitleEng', figureTitleEnglish,...
                          'footerEng',      footerEnglish,...
                          'figureTitleNor', figureTitleNorwegian,...
                          'footerNor',      footerNorwegian...
                          ); 

% Add the nb_graph_adv object to the nb_graph_package object
package.add(plotterAdv);


%% Setting up another graph and adding it to the graph package

% Reading data
data = nb_ts(rand(36,2),'','2008Q1',{'QUA_VAR3','QUA_VAR4'});

% Initialize an nb_graph_ts object with the above data
plotter = nb_graph_ts(data);

plotter.set('graphStyle',       'mpr',...
            'variablesToPlot',  {'QUA_VAR3','QUA_VAR4'},...
            'legends',          {'Variabel tre','Variabel fire'},...
            'legPosition',      [0.1 0.7],...
            'yLim',             [0,8],...
            'ySpacing',         1 ...
            );

figureTitleNorwegian = {['Sammenligning av variabel tre^{1)} '...
                        'og variabel fire.'],...
                        plotter.timespan('')};

footerNorwegian      = {'1) Variabel tre er ikke variabel fire.',...
                        'Kilde: MATLAB'};

figureTitleEnglish   = {['Comparison of the third variable^{1)} '...
                        'and the fourth variable.'],...
                        plotter.timespan('english')};

footerEnglish        = {['1) The third variable is not the '...
                        'fourth variable'],...
                        'Source: MATLAB'};
              
legendsEng           =  {'Third variable',...
                         'Fourth variable'};

figureNameNor        = {'Eksempel 2'};

figureNameEng        = {'Example 2'};

forecastDate         = {'QUA_VAR3','2013Q3','QUA_VAR4','2013Q2'};                     
                     
plotterAdv = nb_graph_adv(plotter,...
                          'forecastDate',   forecastDate,...
                          'figureNameNor',  figureNameNor,...
                          'figureNameEng',  figureNameEng,...
                          'legendsEng',     legendsEng,...
                          'figureTitleEng', figureTitleEnglish,...
                          'footerEng',      footerEnglish,...
                          'figureTitleNor', figureTitleNorwegian,...
                          'footerNor',      footerNorwegian,...
                          'jump',        3 ...
                          ); 
                     
package.add(plotterAdv);

%% Setting up yet another graph and adding it to the graph package

% Reading data
data = nb_ts(rand(36,2),'','2008Q1',{'QUA_VAR5','QUA_VAR6'});

% Initialize an nb_graph_ts object with the above data
plotter = nb_graph_ts(data);

plotter.set('graphStyle',       'mpr',...
            'variablesToPlot',  {'QUA_VAR5','QUA_VAR6'},...
            'legends',          {'Variabel fem','Variabel seks'},...
            'legPosition',      [0.1 0.7],...
            'yLim',             [0,8],...
            'ySpacing',         1 ...
            );

figureTitleNorwegian = {['Sammenligning av variabel fem^{1)} '...
                        'og variabel seks.'],...
                        plotter.timespan('')};

footerNorwegian      = {'1) Variabel fem er ikke variabel seks.',...
                        'Kilde: MATLAB'};

figureTitleEnglish   = {['Comparison of the fifth variable^{1)} '...
                        'and the sixth variable.'],...
                        plotter.timespan('english')};

footerEnglish        = {['1) The third variable is not the '...
                        'fourth variable'],...
                        'Source: MATLAB'};
              
legendsEng           =  {'Fifth variable',...
                         'Sixth variable'};

figureNameNor        = {'Eksempel 3'};

figureNameEng        = {'Example 3'};                     
                     
plotterAdv = nb_graph_adv(plotter,...
                          'figureNameNor',  figureNameNor,...
                          'figureNameEng',  figureNameEng,...
                          'legendsEng',     legendsEng,...
                          'figureTitleEng', figureTitleEnglish,...
                          'footerEng',      footerEnglish,...
                          'figureTitleNor', figureTitleNorwegian,...
                          'footerNor',      footerNorwegian,...
                          'letter',         1,...
                          'remove',         {'QUA_VAR5','QUA_VAR6'}...
                          ); 
                     
package.add(plotterAdv);

%% Print the graphs to a pdf

% PDF in norwegian
package.writePDF('test_nor','norsk');

% PDF in english
package.writePDF('test_eng','english');


%% Save to excel (To get the fan chart upper and lower bounds in 
% the cell above must be runned)

firstPageNameNor = {'Et eksempel',...
                    'med masse tull'};
firstPageNameEng = {'An example',...
                    'with alot of crap'};
roundoff         = 1;

package.saveData('test_excel_output','both',firstPageNameNor,...
                 firstPageNameEng,roundoff);

